rapidez/core

- resources/js/components/Checkout/Checkout.vue
This will allow payment providers to check if their payment provider has been used.
And it will then allow them to use the order id which is returned after converting the quote
> Add additional info for payment providers to use in the checkout

- resources/views/cart/overview.blade.php
- resources/views/checkout/overview.blade.php
- resources/views/layouts/app.blade.php
This PR adds the ability to overwrite the `robots` meta tag and adds noindex,nofollow to the cart and checkout by default
> Overwrite robots meta tag from pages

- resources/js/components/Graphql.vue
This is necessary, so that from a child nested mutation the parent query can be run in the callback
> Add runQuery to slot scope

- config/rapidez.php
- src/RapidezServiceProvider.php
This PR will add support for seperate themes in Rapidez defined per store_code
The reason this is not set in the config itself is because you loose the dynamic switching between themes once the config is cached causing every store to get the same theme.
Documentation PR: https://github.com/rapidez/docs/pull/20
> Add theme support in Rapidez

- package.json
- resources/js/app.js
- resources/js/components/Listing/Filters/CategoryFilter.vue
- resources/js/webworker.js
- resources/views/components/listing.blade.php
- resources/views/layouts/app.blade.php
- resources/views/listing/filters.blade.php
- yarn.lock
What has changed to improve performance?
- Vue initialisation no longer has to wait for turbolinks to be loaded and finished on the initial request
- Heavy tasks in the category filter have been moved to a webworker saving ~140ms on the main thread
- On the category page we preconnect with elasticsearch reducing tcp handshake overhead when making the actual requests (since they're running in paralel this handshake used to happen multiple times since there was no existing connection to use)
- Preload the stylesheet as it's a critical dependency, this enables early hints to serve it early
- lazily load the filter components since they are not shown on mobile until you click the filter button
> Improve pagespeed generally, improve lighthouse on category page

- resources/js/components/GraphqlMutation.vue
This can by used with 
```javascript
<graphqlmutation
...
:before-request="beforeRequestFunction"
...
```
Where the `beforeRequestFunction` must at least contain
```javascript
function (query, variables, options) {
return [query, variables, options];
}
```
the `query` and `variables` are still observables so it is the functions responsibility to turn these to regular objects if they don't want it to change the original value.
> Add a callback before the requests gets sent to be able to change variable and options

- resources/js/components/Product/AddToCart.vue
Currently the loader on the category pages for add to cart does not disappear since it throws an error that error is not defined
> Remove error parameters from successful response

- src/Models/Scopes/Attribute/OnlyProductAttributesScope.php
Updates to amshopby has added attribute_code to the filter_setting table causing ambiguity errors. This fixes it.
> Make attribute_code more explicit

- resources/js/components/Listing/Listing.vue
- vite.config.js
It is now possible to import the slider component because of https://vitejs.dev/guide/dep-pre-bundling.html
So CommonJS and UMD packages work as well.
The rangeslider now throws warnings when you use it but it does function properly.
I've narrowed it down to it being an issue in Reactivesearch and not the range slider. As the rangeslider functions as expected when used on it's own
Update: 
the warnings were caused by vue being loaded twice, which was due to https://github.com/rapidez/core/pull/157/files#diff-58e6f63d87181b1c6a8cb6e5f1691df04aa32854456efcd52ca71c8541375d26L25
This has now been fixed!
> Import vue-slider-component

- src/Commands/InteractsWithElasticsearchCommand.php
Fix key must be object if mappings or settings are empty
> Fix Key must be object

- phpunit.dusk.xml.dist
- resources/js/app.js
This helps debug potential problems during development or during tests, as notifications automatically disappear after a few seconds
> Log notifications to debug if debug mode is on

- vite.config.js
This helps with compiling Vue smaller as now NODE_ENV get correctly figured out within vue.esm.js
vue.js has development hardcoded, and vue.min.js has production hardcoded.
> Load Vue as ES Module

- src/RapidezServiceProvider.php
This prevents a full page reload when navigating from listing to any other page. The reason this happens at the moment is that we set the data-turbo-track="reload" for all vite tags. This checks only sets it for the main app.js.
> Prevent full page reload when navigating from listing

- src/Facades/Rapidez.php
- src/Rapidez.php
This does have the limitation of not being able to remove closures (`addFallbackRoute(fn() => 'test')`) unless you have access to the exact closure.
All other methods like invokable functions, a specific function on a class etc. get removed correctly.
> Add ability to remove fallback route by action

- src/Http/Controllers/FallbackController.php
See:
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Exceptions/Handler.php#L407-L408
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Exceptions/Handler.php#L415
These are exceptions that get translated to 404 not found exceptions once they get to the handler.
If we run into them while going over the Fallback Routes we should go to the next Fallback Route instead of letting it bubble up and showing a 404 page.
> Catch Exceptions resembling 404

- resources/js/app.js
- resources/js/turbolinks.js
- resources/views/components/listing.blade.php
- resources/views/components/productlist.blade.php
- resources/views/components/reactive-base.blade.php
- resources/views/layouts/partials/header/autocomplete.blade.php
Because reactivesearch pagination and search pushes directly to the History with pushState the Turbo object is no longer present. Using the search params allows us to set both and makes sure users can use the back button as expected.
> Turbo history fallback

- resources/js/app.js
By adding the state it's not needed to update Turbo navigator as well and the back button behaves correctly after pagination as well.
> update history with state so Turbo behaves

- src/Commands/IndexProductsCommand.php
Simple solution to being able to quickly hook in multiple actions around the indexer
Can be used like this (e.g. in `App\Providers\AppServiceProvider:boot`):
```php
Eventy::addAction('index.before', function($context) {
$context->call('rapidez:index:sortings');
});
Eventy::addAction('index.after', function($context) {
$context->call('rapidez:index:additionals');
});
```
> Add Eventy hooks for before/after rapidez indexer

- src/Commands/IndexProductsCommand.php
- src/Events/IndexAfterEvent.php
- src/Events/IndexBeforeEvent.php
Instead now it should be used as such:
```php
Event::listen(IndexBeforeEvent::class, fn($event) => $event->context->call('rapidez:index:categories'));
Event::listen(IndexAfterEvent::class, fn($event) => $event->context->call('rapidez:index:additionals'));
```
> Use Laravel events for indexer before/after

- resources/js/app.js
- resources/js/axios.js
In the old situation the first request that finishes would set loading to false while not every request has finished.
in normal situations this is probably no issue, but during tests or slow connections this could mean running into bugs since not all data has been processed.
> Prevent loading turning false when one of multiple simultaneous finishes

- resources/views/layouts/partials/header/autocomplete.blade.php
For some strange reason, reactivesearch has inconsistent behavior here.
When using suggestions (e.g. DataSearch), `_id` is placed under the `source` object.  
However, this is not the case when using hits (e.g. ReactiveList) in a product listing of sorts.
The result of this is that suggestions weren't given a proper key in the v-for here causing a few issues you might expect from that (images not being unloaded, for example).
> Use suggestion.source._id in data-search component

- resources/js/components/Elements/Slider.vue
The function was used without being imported 😇
> Add useEventListener to imports in Slider.vue

- resources/js/app.js
- resources/js/components/Elements/Slider.vue
This change reduced the render function (With cpu throttling set to 8x) of ~120ms to ~20ms
most other components' render functions also take ~20ms
The ENV variable VITE_PERFORMANCE will allow us to enable additional performance markers. In this case just Vues performance markers. Adding visibility to metrics like these (Only works in Vue developer mode)
> Improve render time, add performance variable

- resources/js/components/Elements/Slider.vue
This adds functionality for the slider to bounce back and forth when it reaches either end, rather than sliding back from slide 99 to slide 0 instantly when it reaches the end (which can be quite jarring).
> Add bounce prop to auto slide in Slider

- resources/js/components/Checkout/Login.vue
- resources/js/components/GraphqlMutation.vue
- resources/js/components/User/mixins/InteractWithUser.js
- resources/js/helpers.js
- resources/js/mixins.js
- resources/js/package.js
- resources/views/checkout/partials/address.blade.php
- resources/views/checkout/partials/create-account.blade.php
- resources/views/layouts/partials/header/account.blade.php
Going from `$root.user` to `$root.user?.id` to check if you're logged in breaks a ton of stuff. There were even still some places in the core itself where this wasn't fixed, so I've also included those here.
> Add loggedin computed helper

- CHANGELOG.md
- resources/js/components/Elements/Slider.vue
Not sure what to do with edge cases yet. For example, say 3 children are visible and one child is 70% visible, do we want to round down and say only 3 are actually visible? We can't always round down of course, as in many cases you might get 3.99 which obviously rounds up to 4.
> Fix the slider to properly calculate slides when there's more than 1 child visible at once

- composer.json
- src/RapidezServiceProvider.php
See:
- https://github.com/laravel/framework/pull/47574
- https://github.com/laravel/framework/pull/47569
for progress in Laravel
This PR adds the following directives new:
- `@slots(['optionalSlot'])`
The following are from rapidez/statamic and will be removed there.
- `@attributes(['id' => 'test', 'name' => 'some_name'])`
- `@return`
- `@includeFirstSafe(['potentially-missing-template', 'another-potentially-missing-template'], $set)`
The folowing macro is new:
- $attributes->hasAny(['href', ':href', "v-bind:href"])
> Add @slots directive, add hasAny macro, move generic directives from statamic

- resources/js/app.js
- resources/js/components/Cart/mixins/GetCart.js
- resources/js/components/Checkout/Checkout.vue
- resources/js/components/Checkout/CheckoutSuccess.vue
- resources/js/components/Checkout/Login.vue
- resources/js/components/Graphql.vue
- resources/js/components/GraphqlMutation.vue
- resources/js/components/Listing/Listing.vue
- resources/js/components/Product/AddToCart.vue
- resources/js/components/User/mixins/InteractWithUser.js
- resources/js/filters.js
- resources/views/cart/overview.blade.php
- resources/views/category/partials/breadcrumbs.blade.php
- resources/views/checkout/steps/login.blade.php
- resources/views/components/breadcrumbs.blade.php
- resources/views/layouts/partials/footer.blade.php
- resources/views/layouts/partials/footer/newsletter.blade.php
- resources/views/layouts/partials/header.blade.php
- resources/views/layouts/partials/header/account.blade.php
- resources/views/layouts/partials/header/autocomplete.blade.php
- resources/views/layouts/partials/header/minicart.blade.php
- resources/views/listing/partials/item.blade.php
- resources/views/product/partials/breadcrumbs.blade.php
- src/Http/Middleware/DetermineAndSetShop.php
- src/helpers.php
Turned named urls into `route()` calls
use the `url()` helper when we're certain the url starts with a `/`
use the `to()` helper if the url might start with a relative path
How Laravel generates the domain for the url can be done in multiple ways:
```php
\Illuminate\Support\Facades\Url::formatHostUsing(fn($root, $route) => 'https://example.com');
\Illuminate\Support\Facades\Url::forceRootUrl('https://example.com');
```
or if you simply want to add a prefix to the url that is possible by using the `X-Forwarded-Prefix` header
As there are multiple ways to set this domain, like getting it from Magento, setting it in configuration, passing it from your reverse proxy i have not made any opinionated code on this.
Depending on the requirements of the project one of these can be used on a …
> Add helpers for adding domain to urls

- resources/js/components/Cart/mixins/GetCart.js
- resources/js/components/User/mixins/InteractWithUser.js
- resources/js/stores/useCart.js
- resources/js/stores/useMask.js
- resources/js/stores/useUser.js
The cart wouldn't get cleared properly since the redirect happened before the cart had been properly cleared.
We now await the clearing before we redirect in the next tick, so watchers have time to respond to changes.
I also noticed that the onLogout event listener was added per instance of interactWithUser, causing this function to be called multiple times. This has been prevented using memoization.
And just in case we now check the current state of tokens before setting the data to the received response, to deter possible race conditions.
> Ensure the cart has been cleared on logout

- src/Commands/ElasticsearchIndexCommand.php
- src/Commands/ElasticsearchIndexer.php
- src/Commands/IndexCategoriesCommand.php
- src/Jobs/IndexJob.php
- src/RapidezServiceProvider.php
As it turns out, eloquent models don't like being cast to an array explicitly with `(array)$item`, as I discovered here.
> Categories index command & small fix

- resources/js/components/Listing/Listing.vue
Currently it tries to sort by the translated string in elasticsearch while displaying the non-translated string on the frontend. This should be swapped 😇
> Swap directionKey & directionLabel

- resources/js/components/Product/AddToCart.vue
This caused a file field to not be updated in the computed property when it is replaced by a different one. Vue reactivity with objects/arrays tends to be fickle like that :)
> Fix reactivity issue when uploading file in productoptions

- resources/js/components/GraphqlMutation.vue
This adds the ability to execute a callback when there's an error in the GraphQL mutation response.
> Add ErrorCallback to GraphqlMutation

- resources/js/components/Elements/Slider.vue
This adds a loop capability to the slider. When you slide back to the first slide, the chunk of items is added to the front of the loop. So this also happens immediately when loading, because you start on the first slide.
Similarly, when you go to the last slide, the chunk is placed at the back of the slider. This is the same thing that, for example, Swiper also does for loop generation.
> Add slider loop option

- src/Models/QuoteItemOption.php
...and avoid hard-erroring out of adding items in the future. In theory this should catch everything.
This broke the rapidez demo because it tried to split "attributes"
> Fix error when adding certain kinds of item to the cart

- resources/js/components/User/mixins/InteractWithUser.js
Right now, logging out usually doesn't work because the `logout` event isn't captured---`window.app.$on` appears to be unavailable available in the created hook, nor in the mounted hook, of a mixin like this.
This was the cleanest workaround I could come up with, this will wait until every other thread is completed by basically putting a new thread at the bottom of the stack.
> Add race condition fallback in onOnce

- resources/js/components/User/mixins/InteractWithUser.js
useMemoize caused a problem because the events got unloaded when switching pages (using Turbo), but the memory of useMemoize did not.
The workaround here is to just check if the event already exists, and if not, add it.
> Remove useMemoize for event, use hacky solution instead

- resources/js/components/Checkout/Checkout.vue
Because this can be set to `0`, causing it to fail :)
> Remove `same_as_billing` from required props

- src/Commands/IndexProductsCommand.php
In theory, you'd think that magento should automatically remove products with visibility 1 from the flat table. However, there are still some circumstances where it does get put in there.
I'm uncertain about the exact specifics of this as I've had trouble consistently reproducing the different scenarios.
> Prevent the indexer from indexing invisible products

- resources/js/components/Search/Autocomplete.vue
Using the auth in the URL doesn't work on chrome (and quite probably other browsers) and is probably a bad idea anyway.
> Grab auth data from es_url

- resources/js/components/GraphqlMutation.vue
As it stands now, mutating will for some unknown reason not be set back to false if you don't have a redirect or a notification. Using a `finally` we can make sure this always works properly.
> Set `mutating` to false in a finally

- resources/views/checkout/steps/success.blade.php
Multisafepay saves the method title under `raw_details_info`
If we cannot get the method title from the default place, we'll try and get it from there.
> Support MSP way of saving method_title

- resources/views/components/listing.blade.php
- src/Commands/IndexProductsCommand.php
- src/Models/Product.php
Reason i'm using the function_score instead of sorting on the field directly is so relevancy will still be used when no positions are given or positions are the same.
> Respect the position per category

- resources/js/stores/useCart.js
When an order is placed as a logged-in user, the shopping cart is not emptied. This fix ensures that it does get emptied after placing the order.
> Clear cart storage

- resources/js/stores/useSwatches.js
This helps prevent repeating request when the API returns an empty array
> Add check if already fetched

- resources/js/components/Elements/Slider.vue
Because cloneNode was used every time a scroll occurred a ton of DOM elements would be created every second.
DOM operations are quite heavy on the browser, thus we only create the copies we need and create the illusion of infinite scroll by resetting the scroll position.
As a bonus the navigation buttons and positions work as intended
> Improve slider performance by influencing scroll position for infinite scroll

- package.json
- resources/views/errors/404.blade.php
- resources/views/layouts/partials/header/autocomplete.blade.php
- yarn.lock
Fixes pages (mainly 404) no longer interacting and having broken styling after a 404 due to Turbo handling 404s differently. CSS changes are needed to always have correct styling on the autocomplete; Reactivesearch injects this in the head, and Turbo doesn't properly restore this.
> Fix broken UI after a 404

- resources/views/cart/overview.blade.php
While we stopped aliasing `entity_id` to `id`, this one seems to have been forgotten about.
> Fix cross-sells field

- src/Http/Middleware/DetermineAndSetShop.php
- src/Rapidez.php
At the moment if any other functions need to be excecuted once we know the current store we use a middleware and assume or force the middlewares to run in the correct order.
This is prone to errors when the execution order is different, or the setStore function has been executed somewhere other than the DetermineAndSetShop middleware
This event allows us to hook and update config during **any** calls to the setStore function, be that in a middleware or in a command
Example usage, forcing a custom root url:
```php
Event::listen('rapidez:store-set', function ($store) {
$baseUrl = config('rapidez.url.' . $store['code']);
if ($baseUrl) {
URL::forceRootUrl($baseUrl);
config()->set('frontend.base_url', url('/'));
}
});
```
> Add event for when setStore had been executed

- resources/js/components/Graphql.vue
- resources/js/components/GraphqlMutation.vue
So it's possible to override this. Useful for example with the reviews; they are store specific. In case you want to show product reviews from another store.
> GraphQL components store prop

- src/RapidezServiceProvider.php
Exclude registerThemes from running in console to prevent caching the wrong theme paths for a specific store code.
> Exclude register themes when running from console

- resources/views/checkout/steps/payment.blade.php
- tests/Browser/CheckoutTest.php
This `onerror` got stuck in an infinite loop causing the page to never go idle, making the tests break.
> Fix dusk tests

- resources/js/components/Checkout/CheckoutSuccess.vue
This is relevant for when external payment providers are used---the checkout step value is lost, causing it to say "step 1 out of X".
We can reasonably assume the success step is always step 4 as it's forced this way with the rest API stuff, but I've overengineered it anyway to not have it be hardcoded.
> Always set step in checkout success to success step

- src/Commands/ElasticsearchIndexer.php
Makes it a little more reliable, as the whitespace tokenizer made synonyms case sensitive.
Could also use the standard tokenizer, shouldn't really make a difference here.
[Tokenizer reference](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/analysis-tokenizers.html)
> Fix usage of whitespace tokenizer

- resources/js/components/Checkout/Checkout.vue
CurrentShippingMethod will update on changes in `checkout.shipping_methods` and `checkout.shipping_method`
Because `checkout.shipping_method` was being watched while `currentShippingMethod` is being used in `selectShippingMethod()`, a race condition could occur where `checkout.shipping_methods` was empty while `checkout.shipping_method` was filled. 
Resulting in `currentShippingMethod.carrier_code` throwing an error breaking the `shipping-information` API request.
By watching `currentShippingMethod` we are also waiting for the `shipping_methods` to be filled before attempting to update the shipping method
> Watch currentShippingMethod instead of shipping_method

- src/Commands/ElasticsearchIndexer.php
- `lowercase` filter makes the searching case insensitive
- `asciifolding` allows the search to ignore accents on letters and other weird unicode stuff
> Use lowercase & asciifolding filters in default analyzer & in synonym analyzer

- resources/views/category/overview.blade.php
- resources/views/product/overview.blade.php
- routes/web.php
- src/Models/Category.php
- src/Models/Product.php
Magento has these urls built in by default, and these are always available in Magento.
When no url rewrite has been made for the specified product or category Magento will automatically publish the `catalog/<x>/view/id/<id>` url to the sitemap. Causing 404s to be found on the sitemap prevously
> Support catalog urls

- resources/js/callbacks.js
- resources/js/components/Checkout/CheckoutSuccess.vue
- resources/js/components/Checkout/Login.vue
- resources/views/checkout/overview.blade.php
This new way of getting the next step number allows us to place the login step on the same step as another simply by extending the Login.vue and overriding the computed nextStep function
> Reduce the usage of hardcoded step numbers

- resources/js/components/Checkout/Checkout.vue
currentShippingMethod is never guaranteed to be an object.
as both shipping_methods and shipping_method need to have a value. and have values matching each other.
Otherwise it will be undefined.
If it is we should also assume no shipping method is selected and let the server know.
the shipping-information request seems to succeed with both `undefined` and `null` so we can safely send them.
> Ensure no current shipping method does not break

- resources/js/fetch.js
This is useful for, for example, the multiple wishlists package which needs both.
> Always add store & authorization header to rapidez API calls

- resources/js/components/Checkout/Checkout.vue
This allows for shipping restrictions to work on, for example, the postcode.
> Send full address to check shipping methods

- resources/js/components/Elements/Slider.vue
In later versions of VueUse the old situation causes:
> TypeError: Cannot read properties of undefined (reading 'mounted')
or
> [Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().
Executing this in the nexttick ensures VueUse can resolve the current Vue instance
> Move resizeobserver to nextTick function

- src/Models/Scopes/Attribute/OnlyProductAttributesScope.php
This way, it's impossible to have an attribute labelled as flat without actually being in the flat table.
> [2.x] Find flat attributes by checking the actual table schema

- src/Commands/ElasticsearchIndexer.php
If you're using a callable dataFilter, this toArray call was being done unnecessarily.
The specific reason I'm doing this now is because Statamic has a bug creating an infinite loop calling `toArray()` on entries under certain specific conditions. This is really just a workaround for that, but I can imagine other situations where the extraneous `toArray()` call is also annoying.
> Remove unnecessary toArray calls in product indexer

- src/Http/ViewComposers/ConfigComposer.php
Right now, if you want to use a swatch (which gets indexed as a long in ES), ES will throw a big ol' error complaining about trying to fuzzy search on a long.
This isn't perfect because `static` fields aren't necessarily text and you can still get ES to index text fields as numbers. But it's at least better than always breaking when using swatches.
> [2.x] Only allow certain types to be searchable in autocomplete

- src/Models/Model.php
This change in combination with the `resolveRelationUsing` function eliminates nearly any need to override models and instead macroing and mixing in functionality
> Implement macroable on all Rapidez Models

- src/Models/Scopes/ForCurrentStoreScope.php
Using a lateral join, which limits the SQL compatibility to [PostgreSQL, MySQL >= 8.0.14, and SQL Server](https://laravel.com/docs/11.x/queries#lateral-joins).
Basically this is fixing the fact that the previous query could only select one thing (caused by the `->limit(1)`). This makes it useful for stuff like grabbing the checkoutagreements.
> [2.x] Fix ForCurrentStoreScope

- resources/js/components/Product/AddToCart.vue
Without this the product is not linked to it's parent, meaning that product options of the parent aren't considered.
Nor are the selected configurable options shown in the cart as you've added a simple product instead of a configurable product
> Fixed parent product link for configurable products

- src/Models/OptionSwatch.php
The OptionSwatch model wasn't extending the Rapidez base model thus it didn't have the global eventy filter for scopes.
https://github.com/rapidez/core/blob/master/src/Models/Model.php#L11
> Also add global eventy filters to optionswatch model

- src/Listeners/Healthcheck/Base.php
- src/Listeners/Healthcheck/ElasticsearchHealthcheck.php
- src/Listeners/Healthcheck/MagentoSettingsHealthcheck.php
- src/Listeners/Healthcheck/ModelsHealthcheck.php
- src/RapidezServiceProvider.php
This checks if any of the models written (or overwritten) in `config/rapidez/models.php` are not extending Rapidez' Model.
And warns if it has found any models.
As this is not breaking to the application the healthcheck will not fail.
Sample output:
> Add health check for usage of Rapidez model

- config/rapidez/models.php
- src/Models/ProductView.php
- src/Models/ReportEvent.php
Magento reads from the `report_event` table to create it's reports. Rapidez currently only inserts the view events into the `report_viewed_product_index` table, hence the reports are not available. 
The data is available so if we want to make this backwards compatible we can run this query in a database;
```sql
insert into report_event (`logged_at`, `event_type_id`, `object_id`, `subject_id`, `subtype`, `store_id`) 
select `added_at`, 1, `product_id`, 0, 0, store_id from report_viewed_product_index
```
> Fix product view report

- resources/js/components/Elements/Slider.vue
Sometimes, the parent `slider` element is not the element directly containing the children. You might have some funky table styling that requires a different approach to the way the slider is built.
For example, this is useful for https://github.com/rapidez/compare because of the way the table is structured.
> [2.x] Allow for separate slider & child containers

- resources/views/layouts/partials/header/autocomplete.blade.php
This PR enables highlighting from elasticsearch in the product listing, which puts the `<mark></mark>` tags around matched text on every product title. This was already enabled by default on categories and any other extra indices, so this is for consistency.
> [2.x] Enable highlighting in autocomplete products

- src/Models/SalesOrder.php
When combined with https://github.com/rapidez/amasty-automatic-related-products/ it will try to query `quote_item` on a quote without actually having that table joined. 
The solution is either to do this, or to update the package and add a join to always make sure quote_item is joined. Which would be preferable?
> [2.x] Remove all global scopes from quote relation

- resources/js/components/Product/AddToCart.vue
Magento rounds prices to 2 decimals before they get multiplied by qty. Not doing this can cause some slightly incorrect prices to be shown on the PDP, especially in combination with tier price discounts.
(More specifically, it converts to the given currency before multiplying by qty by calling `currencyByStore`. This isn't always 2 decimals, see [the ISO 4217 specification](https://en.wikipedia.org/wiki/ISO_4217#List_of_ISO_4217_currency_codes)---9 currencies have more than 2 decimals, and 17 currencies have no decimals at all)
> [2.x] Round prices before multiplying by qty

- src/Models/Customer.php
customer_id existed because before it was joined on.
The right value to use is entity_id which is the keyname of the Customer instance
> Check correct customer id when jwt is used

- resources/css/app.css
During render when vue hasn't replaced the components yet some browsers add styling to the listing component.
There is barely any information on it online however it seems that this was an unused, never implemented component that has been long deprecated.
https://html.com/tags/listing/
however some browsers still come with their own styling for it.
Especially the whitespace: pre; and margin: 1em 0px; is problematic.
display: contents; is because we don't really want vue components that get removed anyways to interact with the layout
> Reset styling of the listing component

- resources/js/components/Product/AddToCart.vue
I've tested this in multiple projects, swatchoptions is not an array here so `.find` is not possible.
2.x: #509
> Convert the object to an array

- resources/js/callbacks.js
- resources/js/components/GraphqlMutation.vue
- resources/js/components/Product/AddToCart.vue
- resources/js/fetch.js
Because an exception would get thrown on failing json the catch would trigger instead of the errorcallback.
Now we throw a separate error if it is caused by GraphQL so we can deal with it differently than we would different FetchErrors
> Correctly deal with graphql exceptions to excecute errorcallback

- resources/js/stores/useCart.js
- resources/views/cart/queries/cart.graphql
- resources/views/cart/sidebar.blade.php
As the fixed product tax [can not be fetched on the total prices](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/WeeeGraphQl/etc/schema.graphqls), we have to individually sum all products together :)
> [2.x] Add fixed product taxes in cart

- resources/views/checkout/partials/sidebar.blade.php
The fixed product taxes already showed up as a segment in the checkout, interestingly. However, this was not shown as the whole sidebar was broken. Fixed that.
> [2.x] Fix sidebar

- resources/js/components/Product/AddToCart.vue
Before if the frontend config was overridden but the new options haven't been added it would cause JS errors causing some breakage on the add to cart
> Prevent causing errors if add_to_cart config is missing

- resources/js/callbacks.js
- resources/js/components/Elements/Slider.vue
- resources/js/components/Product/AddToCart.vue
- resources/js/stores/useCart.js
- src/Models/Scopes/ForCurrentStoreWithoutLimitScope.php
- src/Rapidez.php
When updating a project to Rapidez 2.x i came across these problems. the `auto_select_*` gave an error and the cart items were not reactive in the callback.js.
> Fix missing attributeValues and autoselect config errors

- src/Commands/IndexProductsCommand.php
Sometimes you would want to exclude categories to get indexed, or add something to the query. This is why we need to use the eventy scope here too.
> Also add category scopes eventy filter when indexing products

- src/Models/QuoteItemOption.php
- src/Models/Scopes/ForCurrentStoreWithoutLimitScope.php
- src/Rapidez.php
> [2.x] At least return something when there is a value attached to the option

- resources/js/fetch.js
For some API calls, like the `DELETE` call on a wishlist in the multiple-wishlists package, no data is returned. Of course we could also add some return data to the package there, but we might as well fix this to not be an issue.
The code for this isn't great---it's a little frustrating that there doesn't seem to be a cleaner reliable way to test for json-ness of a response (we could check for the response header but that's not bulletproof).
> [2.x] Don't always assume api call returns json

- resources/js/components/GraphqlMutation.vue
The recaptcha validation fails because it checks the `X-recaptcha` header and not the `Authorization` header.
> Set recaptcha token to right header in graphql mutation

- resources/views/components/slideover/partials/header.blade.php
The back arrow button used `id` instead of `for` and used a weird attributes merge (that didn't include the class in the merge, which broke it). There may have been a use case for it while developing this slideover, but it sure as heck isn't used now.
> [2.x] Slideover header button fix

- resources/js/components/Checkout/CheckoutSuccess.vue
So when you're on the success page and the order can not be found there is nothing to show so we can redirect away.
Normally you won't get here as the success page is wrapped by the checkout component, but for example from payment providers the page is rendered standalone, see:
- https://github.com/rapidez/paynl/blob/master/resources/views/success.blade.php
- https://github.com/rapidez/core/blob/master/resources/views/checkout/steps/success.blade.php
cc https://github.com/rapidez/core/pull/503, where there is already taken care of this. Correct @indykoning?
Internal reference: FSM2-1401 and HDB-792
> Redirect when the order can not be fetched from the success page

- resources/js/components/User/mixins/InteractWithUser.js
While a leftover customer_address_id shouldn't occur it does seem to happen sometimes, causing a request to guest-carts with a customer_address_id.
This prevents it by automatically setting it to null when loading the checkout if the customer is not logged in
> Prevent any leftover customer_address_id

- resources/js/callbacks.js
- resources/js/components/Graphql.vue
- resources/js/components/GraphqlMutation.vue
- resources/js/components/Product/AddToCart.vue
- resources/js/stores/useCart.js
In all different contexts. checkResponseForExpiredCart would be sent different types of data.
I've pulled the arguments of both callback functions of the graphql and graphqlMutation component inline.
Also caught an error where the graphql component's callback component should return variables instead of data to be in-line with graphqlMutation
> Make Graphql and GraphqlMutation errorCallback the same

- resources/js/fetch.js
- resources/js/package.js
This token was already added to the base layout template, so here's using it :)
> [2.x] Add CSRF token to Rapidez API requests

- resources/js/stores/useCart.js
The graphql endpoint only returns the fixed product tax amount for a single quantity regardless of the actual cart quantity.
Also note that---while you're able to set fixed product taxes with up to 4 decimals of precision---Magento will automatically round that to whatever currency you use before doing any calculations with it. As a result we actually do not lose any precision by doing it this way.
> Multiply fixed product tax by item quantity

- resources/js/components/Graphql.vue
This actually happens in the [core cart overview](https://github.com/rapidez/core/blob/master/resources/views/cart/overview.blade.php#L10-L17) (also in checkout theme). This throws a warning in the console any time you open the cart, because the default scoped slot doesn't exist.
> Don't throw warning when GraphQL component is used without slot

- src/Models/Scopes/Product/WithProductAttributesScope.php
When not using `selectAttributes` this scope would return too early and not actually select basic stuff like `entity_id`, causing some relations to break.
> [2.x] Move default selects to always select

- src/Casts/Children.php
Without this check an error was thrown when a child that has nog image, is indexed bij the index products command.
> When child has no images, push empty array.

- resources/js/fetch.js
- resources/js/filters.js
Sometimes, when using the new fetch.js functionality, a doubled `/` will slip through and break some requests. We can filter these out before it happens, just gotta make sure we don't filter out the `://` at the start of a url 😉
> [2.x] Filter out double slashes

- src/Models/Quote.php
Not sure what happened here but these were undefined classes, and you'd get an error when trying to grab the child items or crosssells. Not that we really use this model anymore, so I guess nobody noticed...
> [2.x] Fix casts in quote model

- src/Commands/InstallCommand.php
- src/Listeners/Healthcheck/MagentoSettingsHealthcheck.php
With [Laravel Prompts](https://laravel.com/docs/11.x/prompts) we've some clean CLI prompts, so time for a improved install command with:
- Some ASCII art
- Magento Docker setup
- Validate
- Frontend build
- Packages
- Storage linking
- Indexing
- Config publishing
And some more information when a health check fails. Also the "old v2 behavior" is still present with the `--frontendonly` param.
We *could* fix some of the health check errors, but I think it's good to keep that a manual action so we're not touching the users Magento installation.
I also updated the v3 install docs: https://docs.rapidez.io/3.x/installation.html#install-rapidez
One thing I don't like about install commands is when I don't know what options I've, what the consequences are or what's it's going to do. I tried to …
> [3.x] Improved install command

- resources/views/layouts/app.blade.php
Magento provides a config for this that we can listen to in case it's not set on the page.
> [3.x] Use default meta description from magento

- resources/js/package.js
- resources/views/cart/item.blade.php
- resources/views/layouts/partials/header/autocomplete/products.blade.php
- resources/views/listing/partials/item.blade.php
- resources/views/product/partials/images.blade.php
Refactor of https://github.com/rapidez/core/pull/575
I don't see why we need to guess the position of certain parts of the url like in https://github.com/rapidez/core/pull/575 . I think we can just replace the part from magento. I also removed the (possible) url parameters magento likes to return to make sure the urls can be cached.
V2: #602
> [3.x] ResizedPath shorter helper function

- resources/js/components/Listing/Listing.vue
- resources/js/package.js
- resources/views/cart/item.blade.php
- resources/views/layouts/partials/header/autocomplete/products.blade.php
- resources/views/listing/partials/item.blade.php
- resources/views/product/partials/images.blade.php
Refactor of #575 
I don't see why we need to guess the position of certain parts of the url like in #575 . I think we can just replace the part from magento. I also removed the (possible) url parameters magento likes to return to make sure the urls can be cached.
V3: #629
> [2.x] ResizedPath shorter helper function

- resources/views/cart/item.blade.php
- resources/views/cart/sidebar.blade.php
- resources/views/checkout/partials/progressbar.blade.php
- resources/views/checkout/partials/sidebar.blade.php
- resources/views/components/notifications.blade.php
- resources/views/components/productlist.blade.php
- resources/views/layouts/app.blade.php
- resources/views/layouts/partials/header/account.blade.php
- resources/views/layouts/partials/header/minicart.blade.php
Small frontend tweaks.
Resolved checkout header issue where the "regular" checkout header is rendered when url had checkout/*
> Checkout frontend tweaks and resolved checkout header issue

- resources/js/callbacks.js
Sometimes `error.extensions.category` is not set, and i'm getting a sentry error on that. This check prevents that.
V3: #635
> [2.x] Fix error of undefined when extensions is not set

- resources/js/stores/useUser.js
The functions from login have only been moved to their own function.
This lays the foundation for having one piece of logic for all ways of logging in, e.g. login-as-customer, social-login etc.
The only responsibility of those modules, would be acquiring a customer token.
2.x: #637
> Add loginByToken function

- resources/views/checkout/steps/login.blade.php
As it turns out, the standard core functionality of the login is always self-contained within a form. As long as you don't try to get rid of this and merge it with another step (say, the credentials step), this being its own step works without the need for this check.
This broke the dusk tests as the login form got blocked by this check, making it impossible to continue.
(3.x will require some more investigation w.r.t. a one-step checkout)
> [2.x] Remove password check

- resources/views/checkout/steps/login.blade.php
See also #638 
In this case the partial-submit will fail if it can't log in, meaning that the whole issue we had with this login bug actually exclusively ended up laying with the checkout theme and its merging of the login step with the credentials step, and only in 2.x.
> [3.x] Remove password check

- resources/js/components/Product/Images.vue
When you have a product with super attributes, the amount of images in the images array can change depending on what option you select.
The problem is as follows:
- Go to [this product](https://demo.rapidez.io/stellar-solar-jacket.html) on the demo shop and click on the third image
- Change the selected color to either blue or yellow
- The product image on the left will break
What happens here is that the code still has `active` set to `2`, and when we change to the other jacket the images array no longer has a third image, which means it tries to show an undefined image. This then ends up showing the placeholder image that's normally hidden behind.
With this change we clamp the `active` value to make sure it can never go out of bounds (unless the array ends up having 0 images which I've …
> [2.x] Fix image breaking when switching

- resources/js/package.js
- resources/views/listing/partials/item.blade.php
- resources/views/product/partials/gallery/slider.blade.php
There's no reason to use the resizedpath helper in places where it's not needed. It will only make the helper unnecessarily complex. The helper function is only needed when graphql returns store specific urls. Which is not the case on the POP, PDP and in product sliders.
V2: #648
> [3.x] Fix image urls

- src/Http/Controllers/FallbackController.php
- src/Rapidez.php
This PR supersedes: https://github.com/rapidez/core/pull/616
Instead of simply calling the given functions we send them through the routing pipeline as is done in Laravel itself
https://github.com/laravel/framework/blob/5527e72efe5d86cf83afe21944a47fe9a0bdc406/src/Illuminate/Routing/Router.php#L797
Which applies the middlewares, but only for the given router.
However this expects a route instead of a route action. Thus we turn it into a route.
and to maintain backwards compatibility, and exact compatibility with regular routing arguments we pass it through the createRoute function
https://github.com/laravel/framework/blob/5527e72efe5d86cf83afe21944a47fe9a0bdc406/src/Illuminate/Routing/Router.php#L554
Otherwise it would only accept `[Class, 'function']` arguments
> Also apply middlewares when running fallback routes

- composer.json
- config/rapidez/routing.php
- src/RapidezServiceProvider.php
Early hints can improve performance and lighthouse scores by returning Preload and preconnect link headers BEFORE the server has it's response ready. So JS, CSS, and fonts could be loaded before your HTML has finished downloading.
lowering the time to first paint, reducing layout shifts caused by fonts, and improving the speed at which the JS can start executing.
This will automatically install the early hints package, and configure it to work with Rapidez and all it's fallback routes.
docs: https://github.com/rapidez/docs/pull/63
(Do we want this in V2 as well?)
> Add support for HTTP/3 Early Hints

- resources/js/components/User/mixins/InteractWithUser.js
The issue we ran into was that if you have one address set as both default shipping and billing when entering the checkout, they will both be the same object and thus have the same reference.
If you then choose to change your addresses inside of the checkout and try to change one of the two separately, they would both end up getting changed at the same time (as they are the same object reference), causing you to be unable to actually have a billing address that's different from your shipping address.
This is easily fixed by cloning the address object before setting it here.
I do not believe this is a problem in 3.x as the checkout works entirely different there 🙂
> [2.x] Clone address when setting

- resources/js/components/Product/Images.vue
- resources/js/package.js
- resources/views/components/productlist.blade.php
- tests/Browser/CartTest.php
- tests/Browser/CheckoutTest.php
- tests/Browser/DialogTest.php
- tests/Browser/HomepageTest.php
- tests/Browser/NewsletterTest.php
- tests/DuskTestCaseSetup.php
This will make Rapidez initialize before marketing scripts, browser extensions and other scripts run.
Improving startup times of Rapidez.
Before:
After:
Currently as draft as we should figure out the best method/event to run this on in order not to impact LCP
> On initial page load run init before turbo:load has been fired

- resources/js/stores/useCart.js
This was just the wrong variable name, should be `cartItem` here but it seems to have been copied from above where it is `item` :)
> [2.x] Fix var name in function

- resources/js/stores/useCart.js
> [3.x] Fix var name in checkAvailability function

- .github/workflows/phpunit.yml
The bug causing the broken phpunit test is hotfixed in 9.1.5 and then permanently fixed in 9.2.0
> [3.x] Set minimum testbench version to 9.2

- resources/js/components/GlobalSlideover.vue
- resources/js/components/GlobalSlideoverInstance.vue
- resources/js/vue-components.js
- resources/views/components/slideover/global.blade.php
- resources/views/layouts/partials/global-slideover.blade.php
Instead of requiring the global state to be changed, listen to emit events instead and take that data.
This makes it easier in the long run for arbitrary pieces of code to open a slideover.
> The issue with using Vue slots at least is that you can't really turn a this.$scopedSlots.xxxxx() into actual html, there is no helper function for it and it only returns something that Vue uses internally to generate the html.
In more detailed terms:
Vue slots are transformed into `VNode`s already, so it has already been transformed into VirtualDOM. Vue's VirtualDOM cannot easily be transformed into plaintext HTML as they don't expose functions for it.
There's a package `vue-server-renderer` but this is meant for server-side nodejs implementation so it has dependencies on functions not available for …
> Remove dependency on global state, use events instead

- resources/js/components/Checkout/Login.vue
When doing this on the `created` hook, we can consistently generate a console error by going to the login page while logged in.
This is because it will try to redirect you to the account overview page, which will then cause turbo to unload the Vue component. Because this happens on the `created` hook, this means it gets destroyed before it is mounted which Vue does not like.
> [2.x] Only check for logged in state on mounted hook

- resources/js/components/Listing/Listing.vue
Since #604 turbo does not load ASAP during the initial page load.
Most of the time you don't notice, but on slow connections or when running `dev` this may cause issues.
This PR adds a fallback to the window if turbo is not available
> Fix getting pagesize from url if turbo is not yet loaded

- resources/views/layouts/partials/header/autocomplete.blade.php
- resources/views/layouts/partials/header/autocomplete/categories.blade.php
It's a bit weird to check for this inside of the partial, and thus needing to explain in the documentation that this is necessary (see https://github.com/rapidez/docs/pull/69)
I'm not sure why I didn't do this originally when doing the refactor here. This is now a slightly breaking change.
> [3.x] Check for resultsType outside of partial

- resources/js/package.js
Some semi-rare cases happen where the page doesn't have the `csrf-token` element, causing there to be a js error here.
I can't really figure out how I might reproduce this issue myself, but I can see it happening in Sentry for multiple users. Could have something to do with a browser extension like an ad blocker that's being a little overly aggressive.
> [3.x] Null coalescing for csrf token

- resources/js/components/Product/AddToCart.vue
On Chrome and Chromium based browsers, you can remove a selected file in a file input by clicking cancel on the dialog. Because of this, you can select a file and then deselect it. This causes an error in this code because it assumes you always have a file.
> [3.x] Fix error on file removal

- resources/views/cart/item.blade.php
- resources/views/cart/queries/fragments/cart.graphql
This fixes the thumbnail in the cart not matching that of the selected variant, instead just showing the main image.
I assume there are other uses for this too, however this was the most noticeable issue.
> [3.x] Allow access to configured variant data on configured product

- package.json
- yarn.lock
The dusk tests failed because npm doesn't really like when the url stays the same but the contents of the package changes. This is what happened after a small PR was merged.
Now that we have tagged a release we can use that tag so that this (hopefully) never breaks again.
> [3.x] Update ReactiveSearch version (fix dusk tests)

- resources/views/checkout/partials/progressbar.blade.php
- resources/views/checkout/steps/success.blade.php
- resources/views/components/notifications.blade.php
- resources/views/layouts/partials/header/autocomplete.blade.php
- resources/views/listing/partials/filter/swatch.blade.php
- resources/views/product/partials/gallery/thumbnails.blade.php
- tailwind.config.js
Ring & outline will now make use of the border color. 
_How to use:_
**Ring**
`ring-2 ring-emphasis` 
**Outline**
`outline-2 outline-emphasis`
The first class `ring-2 outline-2`  is the width for the ring & outline. The second class is the color you want to use. 
See for an example: https://tailwindcss.com/docs/ring-width & https://tailwindcss.com/docs/ring-color. 
----
Updated the tailwind.config. For shadows we have a new variable that we can use: 
```
shadow: {
emphasis: color('--shadow-emphasis', colors.slate[900]),
DEFAULT: color('--shadow', colors.slate[700]),
muted: color('--shadow-muted', colors.slate[500]),
},
```
**Shadow**
`shadow-xl shadow-emphasis` 
_If everybody have approved this Pull request I will update the Pull request [here](https://github.com/rapidez/docs/pull/70)_ …
> Extend neutral color use for shadow, ring & outline

- lang/nl.json
- resources/css/components/price-slider.css
- resources/views/components/listing.blade.php
- resources/views/components/productlist.blade.php
- resources/views/layouts/partials/header/minicart.blade.php
- resources/views/listing/filters.blade.php
- resources/views/listing/partials/item.blade.php
- resources/views/listing/partials/stats.blade.php
- resources/views/listing/products.blade.php
- resources/views/product/overview.blade.php
- resources/views/product/partials/grouped.blade.php
This PR is ongoing and contains a couple of visual improvements to the rapidez core
stuff like responsive views/color changes and such
> [3] Improve frontend 2

- composer.json
- resources/views/layouts/app.blade.php
Within the Rapidez Blade components, we use the peer-checked utility for slideovers and popups. When you open a slideover or popup, you get a full-screen view of the component. However, you can still scroll in the background of the components. To prevent this, you can add class="prevent-scroll" to the <input element. When the input is checked, the <body gets overflow: hidden, removing the scroll ability.
> Prevent body scroll when input checked

- package.json
- resources/js/package.js
- resources/js/stores/useCart.js
- yarn.lock
The code here assumes that `items` on the cart object always exists. However, as is evident from our Sentry logs, this is not always the case. In certain situations, customers may for example end up inside of the cart with an empty cart object.
With this PR I've fixed the specific errors that we've come across in our Sentry logs.
> [2.x] Fix error on cart items not existing

- package.json
- resources/js/components/GlobalSlideover.vue
- resources/js/components/GlobalSlideoverInstance.vue
- resources/js/vue-components.js
- resources/views/checkout/steps/agreements.blade.php
- resources/views/components/slideover/global.blade.php
- resources/views/layouts/app.blade.php
- resources/views/layouts/partials/global-slideover.blade.php
- yarn.lock
This PR changes the global slideover to use the Teleport component so plain html can be passed without trouble
> Implement teleport in slideover

- resources/js/components/Listing/Listing.vue
Searchkit and browsers in general do not like when you do api requests with the auth in the url, a la `http://elastic:rapidez@elasticsearch.local/`
We do the same in [autocomplete.vue](https://github.com/rapidez/core/blob/master/resources/js/components/Search/Autocomplete.vue), using the url helper to split up the url nicely.
> [Instantsearch] Use URL helper to remove auth from url

- resources/views/product/overview.blade.php
Products in elasticsearch do not have a id attribute that corresponds with the entity_id in related_ids and or upsell_ids.
3.x: #714
> [2.x] Query related products on entity id

- resources/views/product/overview.blade.php
Products in elasticsearch do not have a `id` attribute that corresponds with the entity_id in `related_ids` and or `upsell_ids`.
2.x: #715
> [3.x] Query related products on entity id

- config/rapidez/system.php
- resources/js/stores/useUser.js
- routes/api.php
- routes/web.php
- src/Http/Controllers/GetSignedCheckoutController.php
- src/Http/Controllers/SignedCheckoutController.php
This PR offers a secure way to share a customer token and cart mask to Rapidez in order to support a standalone checkout.
the data will be sent as POST data and then stored in the client's cookie. 
So this data will never be visible plaintext.
Next action will be creating a new Magento plugin which calls this with the data and redirecting
> Add endpoint to request a checkout with the given quote hash and customer token

- resources/js/components/Checkout/CheckoutSuccess.vue
This event listener would linger after navigating away from the checkout success, causing any new cart made after that to be destroyed unexpectedly on refresh or closing the window.
> [3.x] Use useEventListener and destroyed hook for clearing cart in success

- resources/views/cart/coupon/add.blade.php
When entering an invalid coupon code, graphql will return a `graphql-no-such-entity` error. `checkResponseForExpiredCart` checks for a `graphql-no-such-entity` error and clears your cart if found. This is obviously not the type of behavior that we want.
It might end up being a good idea to change the check in `checkResponseForExpiredCart` at some point because I'm sure this won't be the only bug.
> [3.x] Don't clear cart on invalid coupon code

- resources/js/components/Product/AddToCart.vue
When a product has only one super attribute, this happens here: https://github.com/rapidez/core/blame/2.x/resources/js/components/Product/AddToCart.vue#L353 
When there's only one super attribute, the cross reference will return right away and because of this the option will never be added to the disabled options array: https://github.com/rapidez/core/blame/2.x/resources/js/components/Product/AddToCart.vue#L370 
3.x: #695
> Fix the disabled options to work if there's only one super attribute

- resources/js/components/Listing/Listing.vue
The current structure will still need Turbo to exist but allows navigator etc. within turbo to not exist.
This can cause problems since turbo might not always be loaded yet.
It actually exists on the window so accessing it using window?.Turbo should allow it to coalesce properly
> Get Turbo from window

- resources/js/components/Product/AddToCart.vue
Currently we were null-coalescing product.super_attributes, however object.keys does not support null being passed.
It requires an object.
For simple products both options and super_attributes would/should be an empty object
> Fixed add to cart for simple products

- lang/nl.json
- resources/js/callbacks.js
- resources/views/checkout/steps/billing_address.blade.php
- resources/views/checkout/steps/payment_method.blade.php
- resources/views/checkout/steps/shipping_method.blade.php
- resources/views/listing/partials/item.blade.php
- resources/views/product/overview.blade.php
This PR adds some UX improvements mainly aimed at the onestep checkout, but are also applicable to the default checkout
More in detail:
Now we send the set billing address when the billing address form has all required fields filled so no errors are logged due to missing fields.
When calling updateCart we choose the last cart we find. When running combined queries this should result in us getting the latest cart data.
Now we show a message that the shipping address is required before showing shipping methods.
(This is also the case for payment methods when it is not a virtual order, otherwise errors will be returned by GraphQL)
Additionally i've fixed the 500 errors due to rapidez-reviews missing
> Improved onestep checkout UX

- resources/views/components/country-select.blade.php
https://github.com/rapidez/checkout-theme/pull/166
The country select is sorted on the `value`. 
For the UX this Pull request will sort based on the name that is visible on the frontend.
> 2.x Sort country-select on name

- src/Http/Controllers/CategoryController.php
- src/Http/Controllers/PageController.php
- src/Http/Controllers/ProductController.php
- src/Models/Category.php
- src/Models/Page.php
- src/Models/Product.php
- src/Models/Scopes/Product/WithProductAttributesScope.php
By default Symfony (and thus by extension Laravel) returns no-cache, private as the cache-control headers.
https://github.com/symfony/symfony/blob/6f4f04b98f6134996a57d21d1851d558a34dc45c/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php#L251
This causes Turbo to skip loading from cache: 
https://github.com/hotwired/turbo/blob/ae14a60e7a5784deeb54cadeb47778693855c57f/src/core/drive/page_snapshot.js#L66
Using the Etag and/or last_modified date (which we have available for categories, pages and products) allows pages to be cached but always needing to be revalidated:
https://github.com/symfony/symfony/blob/6f4f04b98f6134996a57d21d1851d558a34dc45c/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php#L247
This will allow turbo to use the prefetched page instead of having to …
> Remove no-cache from cache-control

- resources/views/errors/404.blade.php
This content comes from magento and may end up causing you to have broken links:
```html
[...]
<a href="{{store url=""}}">Store Home</a>
<span class="separator">|</span>
<a href="{{store url="customer/account"}}">My Account</a>
[...]
```
This fixes that.
> [3.x] Use @content for 404 content

- resources/js/components/GraphqlMutation.vue
If you have a broken mouse that double clicks (or you just click twice very fast for some reason) you can bypass the standard disabled state and mutate twice. Magento generally does not like this---in most cases it will just mean one of the queries is eaten, but sometimes this can break things (e.g. create 2 exact same orders from 1 cart).
> [3.x] Make sure you can't do a mutation twice simultaneously

- resources/js/components/Recursion.vue
- resources/views/layouts/partials/header/autocomplete.blade.php
- resources/views/listing/partials/filter/category.blade.php
Recursively pass scopedslots to the recursion component.
Only create childcomponents for each item in data to prevent infinite recursion.
Unfortunately the root-path removed all categories
> Fix the recursion of the recursion component

- resources/js/components/Checkout/Checkout.vue
- resources/js/components/GraphqlMutation.vue
If you click the "Place order" button twice in a very short timespan (e.g. your mouse is broken and double clicks the button) we have seen a very rare edge case where this seemingly actually causes an order to be placed twice. I was not able to reproduce this locally, however I do believe that's the actual root cause.
Originally I made [a patch](https://github.com/rapidez/checkout-theme/pull/165) that caused the button to disable instantly on click. However, it seems that didn't actually fix the issue and caused a race condition to rarely happen that disabled the button without submitting.
Instead, here's an alternative solution to only fix the double orders thing.
> [2.x] Make sure you can't place two orders at the same time

- src/Listeners/Healthcheck/MagentoSettingsHealthcheck.php
- src/Models/Config.php
- src/Models/Product.php
- src/Rapidez.php
- src/RapidezServiceProvider.php
- src/helpers.php
- tests/Feature/ConfigTest.php
When retrieving a config option you may end up getting a value of `NULL`. The current implementation uses null-coalescing after getting the value, which causes that `NULL` to be replaced by the default value. However, if the config key does actually exist then this is not the correct behavior.
For example, if you don't want a `.html` suffix on your product pages, you set the config value to `NULL`. This then gets converted back into `.html` when indexing products, causing the wrong urls to be indexed.
This PR fixes that by implementing a `default` option into the `getValue` function and using that instead of the null-coalescing operator.
> [2.x] Only apply default value when config option is not found

- resources/js/components/Listing/Listing.vue
- resources/views/category/overview.blade.php
- resources/views/components/listing.blade.php
- resources/views/listing/filters.blade.php
- resources/views/listing/partials/filter/price.blade.php
- resources/views/listing/partials/filter/search.blade.php
- resources/views/search/overview.blade.php
In this PR:
- Wrote very simple custom routing that keeps the URL somewhat readable and doesn't include the index name, also giving us the power to do whatever we want with these url parameters
- E.g.: `...?price=50%3A80&super_color[0]=58&material[0]=Wool`
- Refactored the searchkit & searchkitClient data a bit, as it being computed forced us to have the routing functions within `data` which is definitely not nice (also means you can't actually use `this.` within those functions)
- Removed `<lazy>` around the filters and moved the `<ais-configure [...]/>` to the bottom of the page so that the routing doesn't get cleared by instantsearch before the filters get loaded in
- Removed the `searchTerm` variable as we don't actually need it with the routing working
- Somewhat extracted the index …
> [Instantsearch] Routing

- composer.json
- resources/views/listing/filters.blade.php
Before:
After:
Removed the position right as the slideover opens default on the left side of the screen. 
Needed to add a `<div>` around for the z-index so it will go over evert item as you can see in the screenshot.
> Fix z-index slideover and place it from the left instead of right

- resources/views/category/overview.blade.php
Currently the widgets are rendered, but the content from the sample data isn't really good looking. We could style everything  even more ([luma.css](https://github.com/rapidez/rapidez/blob/master/resources/css/luma.css)) or replace it with something custom, but a listing on every category is the quickest and nobody is actually going to use the sample data.
Leaving the code commented as an example if a user needs it.
> Always render the listing on categories by default

- resources/views/category/overview.blade.php
Reverts rapidez/core#749, as without changing the categories to actually be anchors you'll end up with an empty page. For the test and demo environments I added this to the deploy scripts:
```bash
$FORGE_PHP artisan tinker --execute="DB::update('UPDATE catalog_category_entity_int SET value = 1 WHERE attribute_id = 54')"
$FORGE_PHP artisan tinker --execute="DB::update('UPDATE catalog_category_entity_int SET value = 0 WHERE attribute_id = 69 AND entity_id IN (37, 38)')"
docker exec MAGENTO-CONTAINER bin/magento cache:clean
docker exec MAGENTO-CONTAINER bin/magento indexer:reindex
```
> Revert "Always render the listing on categories by default"

- resources/js/components/Search/Autocomplete.vue
This can be useful when, for example, trying to define `fields` and setting `_source` to false.
> [3.x] Allow for arbitrary options in additionals

- resources/views/components/cookie-notice.blade.php
- tailwind.config.js
We use named z-indexes but the cookie notice didn't used it so it would have go under elements like filters or popups.
> Fix cookie-notice z-index

- src/Http/ViewComposers/ConfigComposer.php
For this value the following options are possible:
- `1`: Excluding tax
- `2`: Including tax
- `3`: Including and excluding tax
With the cast to bool this would always return true. Instead we should check for value `2`.
> [3.x] Use correct show_tax value

- resources/js/components/Listing/Listing.vue
- resources/views/category/overview.blade.php
- resources/views/search/overview.blade.php
Made a simple change that allows you do add simple filter stuff without having to write the whole query object. This only includes two:
- `filterQueryString` which takes a query string like `visibility: (3 OR 4)`
- `filterScoreScript` which lets you modify the scoring by using an ES script.
I've left it quite simple so that we can easily add more options in case we would like them in the future.
Side note: The baseFilters prop is a function on purpose, as we will want to be able to have dynamic things in there in the future. For example, it will be extremely useful in some project to change the filter based on the typed search query.
> [Instantsearch] Add possibilities for simplifying basefilters

- resources/css/app.css
- resources/js/components/Search/Autocomplete.vue
- resources/js/components/Search/InstantSearchMixin.vue
- resources/views/components/highlight.blade.php
- resources/views/layouts/partials/header/autocomplete/categories.blade.php
- resources/views/layouts/partials/header/autocomplete/products.blade.php
- resources/views/listing/partials/item.blade.php
Adds the `ais-highlight` component to the mixin, allowing you to use it anywhere.
Also made a small component that makes sure you don't try to highlight something that's not in the `highlight_attributes` configuration. Instantsearch will, by default, just not show the value at all if it's not there.
Can be used like this:
```blade
<x-rapidez::highlight attribute="name"/>
```
If the JS variable is not named `item` you can specify it:
```blade
<x-rapidez::highlight attribute="description" item="product"/>
```
And you can add styling:
```blade
<x-rapidez::highlight attribute="name" class="text-red-500"/>
```
> [Instantsearch] Make basic highlight component that doesn't break when the attribute is not in the config

- config/rapidez/frontend.php
- config/rapidez/system.php
- src/Http/Controllers/CheckoutSuccessController.php
Added some config to change the redirect path in case of a failed checkout.
> Added config for success fail redirect path

- resources/js/components/Product/AddToCart.vue
This check caused a simpleProduct to never get selected when a configurable product only has one child product.
I've checked a few other scenarios and nothing else breaks as a result of this change.
> [3.x] Don't return early when only 1 child product exists

- resources/js/fetch.js
By not catching and rejecting the promise you will always gets and uncaught exception when using combining graphql.
This breaks the notifying of the graphql-mutation component.
By catching and rejecting the current promise all functionality is restored.
> Correctly handle combiningGraphql allowing catching

- src/Models/Scopes/Attribute/OnlyProductAttributesScope.php
- src/Models/Scopes/Product/WithProductSuperAttributesScope.php
If the `additional_data` column is `EMPTY` (or invalid JSON) instead of `NULL`, this query throws an error. By adding in this check we can fix this.
> [3.x] Make sure JSON can't be empty

- CHANGELOG.md
- resources/js/stores/useAttributes.js
- resources/js/stores/useCart.js
- resources/views/cart/item.blade.php
This PR is a solution to not having option labels in the cart attributes. Sadly the `customAttributeMetadata` query does not support getting the option labels, however `customAttributeMetadataV2` does. We also had to change the mapping a bit.
3.x: #755
> [2.x] Get option labels with attribute options in the cart

- src/Http/Controllers/FallbackController.php
Symfony's isEmpty check explicitly checks the 204 and 304 status codes. Used to signal "noContent" and "notModified"
These are status codes that explicitly state "We processed the request, we don't WANT to send Content" so we must not throw a 404 there.
> [2.x] Allow empty content when isEmpty is true

- src/Http/Controllers/FallbackController.php
Symfony's isEmpty check explicitly checks the 204 and 304 status codes. Used to signal "noContent" and "notModified"
These are status codes that explicitly state "We processed the request, we don't WANT to send Content" so we must not throw a 404 there.
> Allow empty content when isEmpty is true

- resources/js/stores/useCart.js
By returning void we end up getting `undefined` as our taxTotal, which is obviously not correct as it should be 0.
> [2.x] Return 0 instead of void when no taxes

- resources/views/components/productlist.blade.php
When there are more than 999 products in the listing (or, more realistically, you lower this size down to a number that causes pagination), you will end up having the infinite scroll functionality automatically enabled.
In this case that causes any sliders on a page to fetch more data when you scroll to the bottom of the page. Potentially can cause dozens of ES requests and a ton of content shifting.
> [3.x] Add infinite-scroll false by default

- resources/js/fetch.js
When fetches get called earlier than Vue has booted it can be possible that the loading count does not get added, but does get subtracted once the request finishes.
This change will maintain a state wether loadingCount has been tracked when it adds, so it will only get subtracted if the loadingcount has been increased in the first place
> Fixed negative loadingCount

- resources/views/checkout/queries/fragments/orderV2.graphql
- resources/views/checkout/steps/success.blade.php
Note that Magento by default has it hardcoded empty, allowing for plugins to add data (Like purchase order number).
So this will go mostly unused, but i did have a project that wanted it.
> Added additional data to orderV2 graphql

- resources/views/components/autocomplete/input.blade.php
- resources/views/layouts/partials/header/autocomplete.blade.php
Unfortunately we do still need the additional input to prevent the AIS components from downloading prematurely. This way there's a consistent place to modify this.
> Move duplicate autocomplete parts to component

- resources/js/components/Listing/Listing.vue
- resources/js/components/Search/Autocomplete.vue
- resources/js/components/Search/InstantSearchMixin.vue
- resources/js/instantsearch.js
- resources/js/package.js
- resources/views/components/listing.blade.php
- resources/views/components/productlist.blade.php
- resources/views/listing/filters.blade.php
- resources/views/listing/products.blade.php
- src/RapidezServiceProvider.php
- src/helpers.php
In this PR we've moved the components for instantsearch to be lazily imported, this makes it easier to create your own listings without having to register them again. And prepares us for a Vue 3 update
> Lazily load instantsearch globally

- src/Commands/InstallCommand.php
Otherwise you'll get:
> There are no commands defined in the "rapidez-statamic" namespace.
> Just mention the Rapidez Statamic install command

- resources/js/components/GraphqlMutation.vue
Allows you to add a debounce to graphql mutation queries. Useful, for example, when people are likely to spam a button (e.g. a `+` button in the cart).
> [2.x] Add debounce to gql mutation

- resources/js/package.js
See:
https://github.com/rapidez/core/pull/803/files#diff-862a032d6992ba9a24c4278dd9a2ff425bfadcef76f9f721673d86967b5175f8R91
https://github.com/rapidez/core/pull/803/files#diff-010087ab0afdd6b69b98a2360a70cf78c331bd83d02424dfad1927873c66a713R7
It was used everywhere as a property, however it was placed within methods causing errors
(3.x does have this implemented correctly)
> Make queryParams a computed property

- resources/js/components/Listing/Listing.vue
- resources/js/package.js
- resources/views/category/overview.blade.php
We could also remove the filterQueryString here and also replace that with a function we can call inside of the baseFilters, and maybe by that point we could also aggregate those functions into their own file? Not sure what would be nicer here.
Would look something like this:
```
v-bind:base-filters="() => [
queryString('visibility:(2 OR 4) AND category_ids:{{ $category->entity_id }}')
categoryPositions({{ $category->entity_id }}),
]"
```
> [Instantsearch] Remove filterScoreScript

- src/Rapidez.php
The magento-defaults config will only be queried when the default is `false`, see https://github.com/rapidez/core/blob/master/src/Models/Config.php#L84
This was done because we want to be able to have `null` as an actual default. However, it was not yet changed in this function apparently.
(Note that the config function will never actually return this `false`, so we don't need to add `bool` to the return types)
> [3.x] Use correct default default

- resources/js/callbacks.js
- resources/js/stores/useUser.js
- resources/views/cart/sidebar.blade.php
This PR will automatically select the default shipping method on the cart if it does not have an address selected already.
Magento should, and does already set this. But incorrectly, see: https://github.com/magento/magento2/issues/39828
Setting this manually fixes that.
> Automatically select default shipping method if no shipping method is entered

- src/Http/Controllers/ConfigController.php
- src/Models/Scopes/Product/WithProductAttributesScope.php
After #819 i had errors when trying to index or access PDP pages due to
Visibility being a filter attribute.
https://github.com/rapidez/core/pull/706/files#diff-c30e56dd53ffc1b867aebd6fd4ebb19f51b32821dcc882dbff33382189a09039R58
This caused it to look for visibility_value in the flat table.
I've also fixed an error in getting the config.js since prefix can be unset
> Fixed errors indexing and getting config

- resources/js/components/Search/AisStatsAnalytics.vue
- resources/js/components/Search/Autocomplete.vue
- resources/js/components/Search/InstantSearchMixin.vue
- resources/js/fetch.js
- resources/js/instantsearch.js
- resources/views/layouts/partials/header/autocomplete.blade.php
- resources/views/listing/partials/filter/search.blade.php
- routes/api.php
- src/Http/Controllers/SearchController.php
- src/Models/SearchQuery.php
This is an extension on #813
It would be more valuable to show suggested results that actually return results.
We had the idea to apply the insights middleware to get this information: https://www.algolia.com/doc/api-reference/widgets/insights/vue/
Unfortunately the insights middleware does not get provided with the data we want.
We do get the _current_ result count, but not the **total** result count.
The `connectStats` connector provides us with the information we'd like.
The search query and the number of **total** results.
The insights values could still be really valuable for other analytics, thus the events will get fired on the components implementing the instantsearchMixin, which means listeners can be added on the Listing and Autocomplete.
> Keep track of returned results for search queries

- resources/js/fetch.js
Openreplay/sentry overwrites the fetch method with it's own proxy to track requests.
Because Rapidez boots earlier and caches the fetch method in originalFetch it never uses this overridden fetch method
> [3.x] Use the current version of fetch instead of a cached version

- resources/js/fetch.js
> [2.x] Use the current version of fetch instead of a cached version

- resources/views/components/highlight.blade.php
Apparently you can't self-close the ais-highlight tag, or it will break anything that comes after it in the same div. Weird. Either way, fixed that here, allowing for swatchless prices and reviews to be shown again.
> [Instantsearch] Fix closing tag on items breaking some elements

- resources/js/components/Listing/Listing.vue
- resources/views/components/listing.blade.php
- resources/views/components/productlist.blade.php
99% it will be the product index, so having that as default. Also changed the props order to be inline with the docs and importance: https://github.com/rapidez/docs/commit/67e168141d9f07161b17d410eb596f325a40eb01#diff-c4bd4e225533416f9d38a25dec4e436684cfc7a49bf4477df9db229445560d54R170-R188
> Listing default product index

- routes/api.php
- src/Commands/UpdateIndexCommand.php
- src/Http/Controllers/IndexController.php
- src/Listeners/UpdateLatestIndexDate.php
- src/RapidezServiceProvider.php
This PR adds API endpoints to Rapidez to partially reindex searchable models
By default calling the index controller (`api/admin/index/product`) will result in it updating only for the current store.
Stores can be manually set using `{"stores": [1,2,3]}` or to reindex all stores in 1 api call `{"stores": "*"}`
You are required to add "ids" to the request, this will use the qualifiedKeyName so it does not matter wether the database has `entity_id`, `id`, `order_id`, etc. as primary key
There's also a new command `rapidez:index:update` which aims to update changed data on the current index.
It can only be called if the full indexer has been run since it will not create a new index.
And it will not remove from the index. That is what the API endpoint, or the full indexer is meant for.
docs: …
> Implement partial reindexing

- resources/css/app.css
- resources/views/components/quantity.blade.php
Removed arrows in type number on Firefox
> Input type number remove Firefox arrows

- src/Commands/IndexCommand.php
- src/Models/Traits/Product/Searchable.php
- src/Models/Traits/Searchable.php
Removes the need to overwrite the `elasticsearch.php` config file just to change these.
> [Instantsearch] Allow setting of mappings & settings per index for individual models

- src/Commands/IndexCommand.php
- src/Models/Traits/Product/Searchable.php
- src/Models/Traits/Searchable.php
There is a hacky workaround, where you instantiate a new class that has this parent trait (but not this trait) and then call the static function on that. However, that's obviously not a good solution here.
So, instead I've factored the filters out to the index command. I'm not sure if we should keep them within the trait so it can be used elsewhere? Given that it's index-specific I can't imagine any use case outside of it anyway.
> [Instantsearch] Go back to filter method because parent:: doesn't work for trait inheritance

- config/rapidez/frontend.php
- lang/nl.json
- resources/js/components/Search/Autocomplete.vue
- resources/js/components/Search/InstantSearchMixin.vue
- resources/js/instantsearch.js
- resources/js/stores/useSearchHistory.js
- resources/js/vue-components.js
- resources/views/layouts/partials/header/autocomplete.blade.php
- resources/views/layouts/partials/header/autocomplete/history.blade.php
This PR adds the search history in your autocomplete.
This can be controlled and (re)moved using the frontend.php
It will listen to the global size unless overwritten in the config, it will filter the history using the current search
> Added search history in autocomplete

- resources/js/package.js
- resources/js/turbolinks.js
- resources/js/vue-components.js
Due to the turbolinks.js file loading later than Vue sometimes, the teardown wouldn't happen on the first page load.
This fixes that issue
> Reorder turbolinks startup & event to ensure teardown on first page

- resources/views/components/input/range-slider.blade.php
Now the inputs immediately update when moving the slider.
Entering numbers manually is done on change, since on input would force the min/max restriction WHILE typing
> Update inputs with slider, update model AFTER entering numbers

- resources/views/layouts/app.blade.php
- resources/views/listing/partials/item.blade.php
- resources/views/product/partials/gallery/slider.blade.php
This PR adds a simple view transition for a product image to the next page, more to serve as an example to create more.
See the result:
https://github.com/user-attachments/assets/dbb89f15-f40b-434f-bda2-16027177c192
> Added basic view transition

- resources/js/package.js
Different task scheduling between chrome and firefox would cause issues, on firefox the timeout is triggered later than on chromium.
This check will handle all chromium based browsers.
Firefox and safari seem to want the same event so we check chromium
> Fixed navigation on firefox

- resources/views/layouts/partials/header/autocomplete.blade.php
What i noticed was happening when the focus trigger failed was that the paint was triggered "way" later than the focus.
Due to us triggering the focus before the task where the paint was actually done.
After adding the RequestAnimationFrame you can see the focus is triggered in the same task as the paint, allowing the element to be focussed
> [V3] Fixed intermittend error on autocomplete focus

- resources/js/components/Product/AddToCart.vue
The product-super-attribute-changed event is also fired when there is no change in simpleproduct. When making any changes that triggers the computed simpleProduct the event will keep getting fired.
2.x: #865
> [3.x] Only fire product attribute change when it's changed

- resources/js/components/Product/AddToCart.vue
The product-super-attribute-changed event is also fired when there is no change in simpleproduct. When making any changes that triggers the computed simpleProduct the event will keep getting fired.
3.x: #864
> [2.x] Only fire product attribute change when it's changed

- resources/views/components/productlist.blade.php
- resources/views/listing/partials/item.blade.php
- resources/views/listing/products.blade.php
- resources/views/product/overview.blade.php
I've tweaked the product tiles visually. I have done the following:
- Removed border in default product tile, added the border manually in the category overview. Now the product slider doesn't contain the border
- Added correct spacing on the product detail to align the gallery with the products
> Tweaked product tiles and aligned components

- resources/js/components/Listing/Listing.vue
- resources/views/layouts/partials/header/autocomplete/categories.blade.php
- resources/views/layouts/partials/header/autocomplete/products.blade.php
- resources/views/listing/partials/no-results.blade.php
- resources/views/search/overview.blade.php
This PR adds the categories to the "No products found" page after searching.
Visually it looks the same as the search suggestions on the not found page
> Show categories on search page if no results

- resources/js/components/Search/Autocomplete.vue
- resources/views/components/autocomplete/input.blade.php
- resources/views/layouts/partials/header/autocomplete.blade.php
The ais-configure at this spot forced the ais-instantsearch component to reset when the exact search term was used.
This way it no longer resets the autocomplete.
> Removed ais-configure breaking search

- resources/js/components/Listing/Listing.vue
The issue seems to be caused by passing an empty array to the `category_lvl1` which sometimes confuses instantsearch making it filter the `category_lvl1` for an empty string.
passing null instead of an empty array seems to ensure instantsearch will not try to filter it.
> Check if category array has values before passing it

- resources/views/layouts/partials/header/autocomplete/search-suggestions.blade.php
This fixes the weird bug where for a only millisecond you would see `<ais-highlight-0000000000>text<ais-highlight-0000000000/>` in your hits instead of the actual highlight.
This is just a hotfix, as I have not yet found the proper reason for this happening which might allow for a cleaner fix. This specific string is used internally within instantsearch and gets replaced with `<mark>` and `</mark>`, see [here](https://github.com/algolia/instantsearch/blob/5a2d2121c1f82840e59ba69edfe0a4f41450f41b/packages/instantsearch.js/src/lib/utils/escape-highlight.ts#L6)
> [Instantsearch] Hotfix for highlight flickering

- src/Http/Controllers/ProductController.php
When no product options are selected it should not pick the first child, but the parent.
> [Instantsearch] Fix wrong color being shown because it always picked the first child

- resources/views/layouts/partials/header/autocomplete/history.blade.php
- resources/views/layouts/partials/header/autocomplete/search-suggestions.blade.php
The search broke for the search suggestions and history. We also didn't yet have a `data-turbo="false"` on the search suggestions, where we potentially redirect to an external URL.
The `data-turbo="false"` ended up fixing the search breaking bug, however I don't know if this will be the best solution. For that I've made an internal issue to look at this (RAP-1377).
Finally, I changed the `v-bind:href` in the history file just to be consistent with the one in the search suggestions.
> [Instantsearch] Add data-turbo to search suggestions & history, make route + replace usage consistent

- resources/js/components/Listing/Listing.vue
The router still calls the window title function after the listing has been destroyed. This is because all of the filters get destroyed, which causes InstantSearch to update the state, which includes calling this function.
By checking whether the listing has been destroyed and returning `null` when it has been, we avoid this from affecting the title.
> [4.x] Fix title being set after destroy

- resources/views/checkout/steps/billing_address.blade.php
This PR will prevent the 
error when unchecking & checking same as shipping when no valid shipping address was entered.
If same as shipping is selected we check wether a shipping address has been set before sending
> Validate shipping address before sending same as shipping

- src/Commands/IndexProductsCommand.php
This PR maps the special price attribute to a double so it can be used in a range query to elasticsearch.
> [2.x] Map special price to double so it can be used in range query

- src/Commands/IndexProductsCommand.php
This PR maps the special price attribute to a double so it can be used in a range query to elasticsearch.
> [3.x] Map special price to double so it can be used in range query

- resources/views/checkout/partials/address.blade.php
Fixes for the credentials form: 
**Before multistep:**
**Before one step:**
**After multistep:**
**After onestep:**
_There are some conditional fields for example `region field` that will shown when selecting Italy_
_Also added checks in the styling when the `Addition` is shown or not_
Internal ref (RAP-1404) show a  toggle to switch between Consumer and Business
_Made also the gap a little big bigger between the fields._
> Credentials form fixes

- composer.json
- src/RapidezServiceProvider.php
This PR adds the opensearch engine compatibility by adding
```env
SCOUT_SEARCH_BACKEND=opensearch
```
to your .env
There will also be some mapping done to support the flattened type.
https://github.com/rapidez/laravel-scout-elasticsearch/commit/11c978986b1f52744370a1891100b175d4857024
docs: https://github.com/rapidez/docs/pull/100
> Implement custom elasticsearch engine to support opensearch

- resources/js/components/Product/AddToCart.vue
- resources/views/product/partials/super_attributes.blade.php
This fixes two issues:
- Super attributes didn't get sorted at all in product listings, causing them to always be sorted by value.
- Super attributes got sorted by `sort_order`, however when there are duplicate `sort_order` values the tiebreaker should be alphabetical based on label.
I've also lightly cleaned up the `getOptions` code here.
> [4.x] Sort super attributes correctly

- phpstan.neon
- resources/views/listing/partials/item/super_attributes.blade.php
- src/Models/Category.php
- src/Models/Product.php
We still used the old `getXxxAttribute()` functionality in a few places. This PR replaces all of those with the Attribute cast.
> [4.x] Use Attribute casts instead of getXxxAttribute

- src/Listeners/Healthcheck/ElasticsearchHealthcheck.php
- src/Listeners/Healthcheck/OpensearchHealthcheck.php
- src/RapidezServiceProvider.php
Fixes: rapidez/rapidez#99
This PR adds an additional health check to check opensearch reachability.
Now also utilising Laravels http facade in order to use admin credentials so the web user does not need access to the Elastic/opensearch servers status and version.
> Updated healthcheck to check opensearch as well

- resources/views/cart/queries/fragments/cart.graphql
These were present in the old query, but seem to have been forgotten in the update to the fragment.
> [3.x] Add backorder & fixed product taxes

- src/Models/Traits/Searchable.php
`Arr::partition()` is Laravel 12 only.
This was missed by the automated tests because we don't actually test the indexer. Might be worth changing that?
> [4.x] Use collect()->partition() to keep L11 support

- resources/views/components/slider.blade.php
This bit of code caused the selected index on the slider to be off by one. Fixed by subtracting one.
> [4.x] Fix off-by-one error

- resources/views/components/listing.blade.php
- resources/views/components/productlist.blade.php
- resources/views/layouts/partials/header/autocomplete.blade.php
- resources/views/layouts/partials/header/autocomplete/history.blade.php
- resources/views/listing/partials/filter/category.blade.php
- resources/views/listing/partials/filter/price.blade.php
- resources/views/listing/partials/filter/selected.blade.php
- resources/views/listing/partials/filter/swatch.blade.php
- resources/views/listing/partials/item.blade.php
- resources/views/listing/partials/toolbar/pages.blade.php
This is kind of a workaround, as a fix for this exact issue has eluded me.
---
When you have a Vue component around the `ais-instant-search` component, with a v-slot using the `{ a, b, ... }` notation, for example like this:
```blade
<toggler v-slot="{ isOpen, toggle }">
<div>
<ais-instant-search>
[...]
</ais-instant-search>
</div>
</toggler>
```
If *any* of the variables that exist within that slot scope change(in a non-deep way)---even just a completely unused boolean going from true to false---the whole instantsearch tree gets refreshed. Adding a key does not resolve this issue.
Something of note here as well is that when this tree gets refreshed, the classname of the instantsearch element changes from:
```html
<div class="Ais-InstantSearch">
```
to:
```html
<div class="[object …
```
> [4.x] Use slot props in listings to avoid instantsearch doing full re-renders

- src/Models/Traits/Product/Searchable.php
This PR basically takes all indexable attributes, tries to determine their type and pass it to elasticsearch.
The biggest usecase for this is custom range sliders which WILL break if the type is set to a textual type.
It's also some data optimisation for Elasticsearch.
> Automatically parse types to set as mappings

- resources/js/components/VueTurboFrame.vue
- resources/js/vue-components.js
Heavily inspired by https://github.com/ElMassimo/vite_ruby/discussions/369#discussioncomment-9743096
The `vue-turbo-frame` component lets you load Vue components right inside Turbo Frames. Before this, Vue components generally wouldn't load or render correctly when content came in via a Turbo Frame.
Usage is pretty much the same as a normal `turbo-frame`, but I've pre-configured a couple of useful props that we usually want on there anyway.
Here's how you'd use it in your main Blade template:
```html
<vue-turbo-frame src="/path-to-your-content" id="my-frame">
<div>Loading cool stuff...</div>
</vue-turbo-frame>
```
And then, the Blade file that `/path-to-your-content` serves would look something like this, containing your actual `turbo-frame` and Vue component:
```blade
<turbo-frame …
```
> Add vue-turbo-frame component

- resources/js/components/Checkout/CheckoutLogin.vue
if you can change the email field, you're a guest and your guest email should be set. However, this did not happen in checkout setups where the login step is combined with something else (e.g. the onestep checkout) which meant your email didn't actually get set until you go to the next step.
By hooking into this function we change that. Maybe we should also check if the email is valid before we go into either of these functions?
> [4.x] Set guest email on change

- resources/views/components/autocomplete/input.blade.php
- resources/views/layouts/partials/header/autocomplete.blade.php
- tests/playwright/search.spec.js
Follow up on https://github.com/rapidez/core/pull/964, it seems we don't need any id's at all.
> Unique autocomplete ids

- resources/views/layouts/partials/header/minicart.blade.php
Everything else works correctly with the `showTax` variable, but not this one.
> [4.x] Add row total including tax for minicart

- resources/js/components/Listing/Listing.vue
- resources/js/package.js
The category positions script broke if used on something that didn't have this attribute, as it didn't actually check for existence of this attribute. Because we put the query on by default in the listing that means that everything that only uses `ais-index` also gets this attached. For example, the category listing on the `no-products` view and every non-product list in the autocomplete.
I've added a check to fix it.
Also added a fallback on the category in the Listing. This doesn't fully fix a weird bug I've run across, but it's a symptom of it.
> [4.x] Fix category positions script & add category fallback

- resources/js/components/Listing/Listing.vue
This PR aims to fix the issue that occurs when you're searching in a category until no results are found, you then remove your search query and it can still not find anything.
The reason this change works is because in JS Arrays and Objects are references.
So the splice call is not being executed on `let category`, instead on `data.hierarchicalMenu.category_lvl1` causing any information there to get lost.
Using the spread operator we make a clone instead, thus having no side-effects on the data in `category_lvl1`
> Prevent split on category_lvl1 reference

- .github/workflows/playwright.yml
- tests/playwright/pages/BasePage.js
This should raise the speed score as it no longer tries a render blocking 404 css download which is in the Magento demo by default with `<link rel="stylesheet" type="text/css"  media="all" href="{{MEDIA_URL}}styles.css" />`
> Remove render blocking 404 download

- tests/playwright/pages/CheckoutPage.js
So when you're already logged in it's possible to simply do this to place an order:
```
const productPage = new ProductPage(page)
const checkoutPage = new CheckoutPage(page)
await productPage.addToCart(process.env.PRODUCT_URL_SIMPLE)
await checkoutPage.checkout()
```
Used in: https://github.com/rapidez/account/pull/73
> Playwright checkout page optional login possibility

- lang/nl.json
- resources/views/product/partials/options/checkbox.blade.php
- resources/views/product/partials/options/drop-down.blade.php
- resources/views/product/partials/options/radio.blade.php
This PR adds the missing radio and checkbox product options.
Also the dropdown has been updated to allow "No selection" when it's not a required option:
> Added checkbox and radio options

- resources/js/components/Listing/Listing.vue
- resources/js/components/RecentlyViewed.vue
- resources/views/components/productlist.blade.php
- resources/views/listing/products.blade.php
- resources/views/widget/recently-viewed.blade.php
So the products in the widget are sorted in order of visits instead of by the default; score.
- We could sort directly in the DSL query with a custom script but this feels cleaner and it is better readable
- As `transform-items` is the only prop on the [ais-hits component ](https://www.algolia.com/doc/api-reference/widgets/hits/vue/) we could use I added it on the listing component to passthrough. This way we can just set in on the productlist component (as all attributes will be set on the listing Vue component) without the need of a Blade component prop with all possible variants (with and without v-bind, etc)
> Recently viewed widget sorting

- resources/views/search/overview.blade.php
This would show `Search for: {{ $root.queryParams.get('q') }}` for a split second before turning into the correct text, because vue hadn't loaded in yet. This could be fixed with a v-cloak, but I think this is neater.
> [2.x] Fix search overview header not showing properly on page load

- resources/js/components/Checkout/CheckoutLogin.vue
If your email was pre-filled (due to already being written into the cart) it didn't get re-checked for availability. This meant that the password field would not appear if you entered an existing email, and you'd have to change it to something else and change it back to log in.
This PR checks email availability once on mount if it's filled and you're not logged in.
> [4.x] Check email availability if it's prefilled

- resources/js/components/Checkout/Checkout.vue
`region_id` and `region_code` can be used interchangeably in the checkout. Only one was currently optional, so here I've added the other.
> [2.x] Add region_code to optional attributes

- resources/views/layouts/partials/header/autocomplete.blade.php
- resources/views/layouts/partials/header/autocomplete/no-results.blade.php
- resources/views/layouts/partials/header/autocomplete/search-suggestions.blade.php
When a custom size was passed in the config it would cause the browser to completely freeze.
This seems to have been caused by the existence of the `ais-configure` element within an `ais-autocomplete` element which it did not like.
I've removed the dependence on `currentRefinement` outside of the autocomplete component.
> Fixed crash when custom size has been passed
