resources/js/components/Elements/Slider.vue

This PR adds an optional property to be passed to the slider component to define which ref is a slider.

Add optional reference prop to slider

---

package.json
resources/css/components/vue-slider.css
yarn.lock

As it doesn't play nice with decimals. In the new `@appbaseio/reactivesearch-vue` version everything get's rounded.

Price slider fix

---

resources/js/app.js
resources/js/components/Listing/Listing.vue
resources/js/components/Product/AddToCart.vue
resources/js/lodash.js
resources/js/reactivesearch.js
resources/js/turbolinks.js
resources/js/vue.js
resources/views/layouts/app.blade.php
webpack.mix.js

Upgrade notes; make sure all the Lodash methods and Reactivesearch components are added if you're using any others as not everything is loaded by default anymore. Also make sure the new `manifest.js` and `vendor.js` files are loaded in the head in case it's overwritten.

Javascript size improvements

---

package.json
resources/js/app.js
resources/js/components/Listing/Filters/CategoryFilter.vue
resources/js/components/Listing/Listing.vue
resources/js/turbolinks.js
resources/js/webworker.js
vite.config.js
yarn.lock

This builds further on #157 to prevent conflicts caused by
https://github.com/rapidez/core/pull/157/files#diff-58e6f63d87181b1c6a8cb6e5f1691df04aa32854456efcd52ca71c8541375d26R25

Fix errors for CategoryFilter component

---

resources/views/cart/overview.blade.php
resources/views/layouts/app.blade.php
resources/views/layouts/partials/footer.blade.php
resources/views/layouts/partials/header.blade.php
resources/views/layouts/partials/header/minicart.blade.php

Added some styling for minicart & cart. 
Changed styling for checkout header & footer.

JFE-665 + JFE-651 Checkout header + footer | Minicart + shoppingcart

---

resources/views/checkout/overview.blade.php
resources/views/checkout/partials/form.blade.php
resources/views/checkout/partials/progressbar.blade.php
resources/views/checkout/partials/sidebar.blade.php
resources/views/checkout/steps/credentials.blade.php
resources/views/checkout/steps/payment.blade.php
resources/views/components/radio.blade.php
resources/views/layouts/partials/footer.blade.php

Styling checkout credentials form + payment page

JFE-650 + JFE-661 Credentials form checkout | Payment page checkout

---

resources/js/components/Checkout/Login.vue

Allow logging out from the checkout login section

---

resources/views/cart/overview.blade.php
resources/views/layouts/partials/header/autocomplete.blade.php
resources/views/listing/partials/item.blade.php
resources/views/product/partials/images.blade.php

Needed for: https://github.com/rapidez/image-resizer/pull/20

Prefix images coming from Magento

---

src/Commands/IndexProductsCommand.php
src/Events/IndexAfterEvent.php
src/Events/IndexBeforeEvent.php

https://github.com/rapidez/core/pull/226

Use laravel events for before/after index

---

resources/views/layouts/partials/header/autocomplete.blade.php

https://github.com/rapidez/core/pull/248

Use suggestion.source._id in datasearch

---

resources/js/components/Elements/Slider.vue

The throttle function triggers the function at most every 150ms on both the leading edge and trailing edge.
Meaning initial response will be instant and the function will be triggered after you stop scrolling as well.
every 250ms made the buttons disappearing feel sluggish when triggering the scroll by clicking the buttons. every 150ms did not.
Before:
After (timing is from an event not firing the function, firing the function costs the same):

Throttle the scroll event and set it to passive

---

resources/js/components/Elements/Slider.vue
resources/js/package.js

https://github.com/rapidez/core/pull/261

Improve render time, add performance variable

---

src/Models/OptionSwatch.php

https://github.com/rapidez/core/pull/266

Aggregate swatches by value id, sort swatches later

---

resources/js/components/Elements/Slider.vue

https://github.com/rapidez/core/pull/267

Update slider with bounce

---

resources/js/components/Elements/Slider.vue

Slider wasn't working correct with the EventListener.

Fix Slider

---

config/rapidez.php
src/Http/Controllers/FallbackController.php

https://github.com/rapidez/core/pull/228

Add caching to fallback routes

---

resources/js/components/Cart/mixins/GetCart.js
resources/js/stores/useCart.js

So that addresses don't stay alive when you log out

Clear addresses along with cart clear

---

resources/js/components/Elements/Slider.vue

Makes it reactive and calculate properly on page load, where it previously didn't under certain conditions

slidesTotal as computed

---

resources/views/listing/partials/filter/price.blade.php

Fixes the dynamic range slider

Use dragOnClick and disable keyboard

---

src/Commands/ElasticsearchIndexer.php

Cute lil helper function that laravel has, also allows dot notation to be used for deeper nesting if necessary 😇

Use data_get to allow both stdClass & arrays to be used

---

tailwind.config.js

for z-indexes and notification styling

Use new config path in tailwind config

---

config/rapidez/models.php
src/Commands/ElasticsearchIndexCommand.php
src/Commands/ElasticsearchIndexer.php
src/Commands/IndexCategoriesCommand.php
src/Commands/IndexProductsCommand.php
src/Models/SearchSynonym.php

Set `$synonymsFor` before indexing, or manually prepare the indexer with it, to use the synonyms :)

Add search synonyms

---

src/Http/Middleware/CheckStoreCode.php
src/RapidezServiceProvider.php

Docs: https://docs.rapidez.io/1.x/extending.html#routes (https://github.com/rapidez/docs/commit/7cafae2a30902fa26c169ef1af6195c5e2bd6e13)

Store code route middleware

---

config/rapidez/models.php
src/Commands/IndexProductsCommand.php
src/Models/Product.php
src/Models/ProductReviewSummary.php

Which currently can be used freely but gives a good start to refactor https://github.com/rapidez/reviews later.

Product review summary model

---

resources/js/components/Checkout/Checkout.vue
resources/js/components/Checkout/CheckoutSuccess.vue
src/Models/Quote.php

These changes were required to support https://github.com/rapidez/paynl/pull/14

Add events to handle order placing independently

---

src/RapidezServiceProvider.php

this adds
```blade
@storecode('store1')
@endstorecode
@storecode(['store1', 'store2'])
@endstorecode
```
or alternatively
```blade
@storecode('store1', 'store2')
@endstorecode
```

Add new storecode if directive

---

package.json
resources/js/turbolinks.js
yarn.lock

See: https://discuss.hotwired.dev/t/lighthouse-inp-scoring-lower-than-turbo/5648

Upgrade turbo for link preloading, show progressbar quicker

---

resources/views/layouts/app.blade.php

And used the `@config` directive for the page title stuff.

Output design/head/includes

---

package.json
yarn.lock

[1.x] Use forked reactivesearch

---

composer.json
src/Commands/ElasticsearchIndexer.php
src/Jobs/IndexJob.php

Replace cviebrock/laravel-elasticsearch with mailerlite/laravel-elasticsearch as cviebrock/laravel-elasticsearch is abandoned

Migrate Elasticsearch package

---

resources/views/checkout/partials/address.blade.php

Used in https://github.com/rapidez/postcodeservice/pull/4

Fire postcode change event in checkout

---

src/Models/Scopes/Attribute/OnlyProductAttributesScope.php

Forgot to make this one for 1.x (see also #452)

[1.x] Find flat attributes by checking the actual table schema

---

resources/js/components/Search/Autocomplete.vue

This is no longer called data, rather it's called body.

Fix autocomplete fetch

---

CHANGELOG.md
resources/js/components/Listing/Listing.vue
resources/views/components/listing.blade.php

Moved to listing.vue

---

resources/js/components/Product/AddToCart.vue
resources/views/product/partials/options/multiple.blade.php

This makes it possible for multiselect & checkbox options to work

Add support for multiselect values

---

src/Models/ProductLink.php
src/Models/SalesOrder.php
src/Models/SalesOrderAddress.php
src/Models/SalesOrderItem.php
src/Models/SalesOrderPayment.php
src/Models/SearchQuery.php
src/Models/SearchSynonym.php

Following https://github.com/rapidez/core/pull/487 it seems like that wasn't the only file not extending the rapidez base model, this updates the rest

Use Rapidez base model for all models

---

resources/views/components/button/base.blade.php
resources/views/components/button/index.blade.php
resources/views/components/button/outline.blade.php
resources/views/components/button/primary.blade.php

We don't need al of this classes on the button. 
- I removed classes from the base button that we don't need.
- Placed paddings on the buttons where we need it.

Removed classes from base button | Placed paddings on buttons where needed

---

resources/views/components/button/base.blade.php
resources/views/components/button/index.blade.php
resources/views/components/button/outline.blade.php
resources/views/components/button/primary.blade.php

Revert "Rearranged the button classes (#460)"

---

resources/views/cart/overview.blade.php
resources/views/product/partials/addtocart.blade.php
src/Models/Quote.php
src/Models/Scopes/Product/WithProductStockScope.php
src/RapidezServiceProvider.php

Will wait to do the 2.x version of this until this is approved.

[1.x] Add backorders

---

src/Models/Product.php
src/Models/ProductImage.php

1.x: https://github.com/rapidez/core/pull/501

Sort images in gallery by position in Magento

---

src/Models/QuoteItemOption.php
src/Models/Scopes/ForCurrentStoreWithoutLimitScope.php
src/Rapidez.php

I've only just run into this being a problem by using a package that adds custom options here that aren't represented by magento options.

[1.x] Always attempt to decode attribute value

---

src/Models/Customer.php
src/Models/CustomerGroup.php

[2.x] Add customer group relation

---

resources/js/components/GraphqlMutation.vue

This fixes the tests where email should show it is already subscribed

Set error message on graphql errors as well

---

src/Listeners/Healthcheck/MagentoSettingsHealthcheck.php

Missing super attributes cause broken price calculations

Add health check for super attributes

---

resources/js/components/Product/AddToCart.vue

Also prevents breaking price calculations, with additional debugging info

Prevent price addition errors in sliders

---

src/Models/Quote.php

Adding a GREATEST here to make sure you don't get to see what the "negative stock" may be on a product.

[1.x] Don't expose negative stock values

---

resources/views/components/slideover/index.blade.php

Not merging like this doesn't (always) work right. Now it will work as intended.

[2.x] Merge class into slideover inputs

---

src/Commands/InstallCommand.php

To keep code formatting in projects inline with the core.

Publish the .prettierrc.js file with the install command

---

resources/js/components/Listing/Listing.vue

This is not a piece of JS code, this is ES code. Which needs to be sent in as a string so that ES can parse it :)

[2.x] Query script needs to be a string

---

resources/views/components/checkbox.blade.php
resources/views/components/filter/heading.blade.php
resources/views/listing/partials/filter/category.blade.php

A few frontend fixes that came from using these new filters in a new project :)

[2.x] Category filter also using the standard heading

---

resources/views/layouts/app.blade.php
src/Http/ViewComposers/ConfigComposer.php
src/RapidezServiceProvider.php

Docs: https://github.com/rapidez/docs/pull/50

Make icon deferring default

---

resources/views/cart/overview.blade.php
resources/views/checkout/pages/credentials.blade.php
resources/views/checkout/pages/login.blade.php
resources/views/checkout/pages/onestep.blade.php
resources/views/checkout/pages/payment.blade.php
resources/views/checkout/partials/progressbar.blade.php
resources/views/checkout/partials/sidebar.blade.php
resources/views/checkout/steps/payment.blade.php
resources/views/checkout/steps/payment_method.blade.php
resources/views/checkout/steps/shipping_method.blade.php
resources/views/checkout/steps/success.blade.php

- Responsive fixes
- (Small) Visual changes

Frontend - Graphql checkout fixes

---

postcss.config.js

[2.x] Use correct object structure in postcss config

---

resources/js/callbacks.js
resources/views/checkout/pages/credentials.blade.php
resources/views/checkout/pages/login.blade.php
resources/views/checkout/pages/onestep.blade.php
resources/views/checkout/pages/payment.blade.php
resources/views/checkout/steps/billing_address.blade.php
resources/views/checkout/steps/login.blade.php
resources/views/checkout/steps/payment_method.blade.php
resources/views/checkout/steps/shipping_address.blade.php
resources/views/checkout/steps/shipping_method.blade.php

The name wasn't clear on what it did and what it was used for. The new name and attribute might clarify this more.
docs: https://github.com/rapidez/docs/pull/60

Rename submit fieldsets function

---

lang/nl.json
resources/views/checkout/steps/login.blade.php

See: https://github.com/rapidez/core/pull/613

[3.x] Make sure you actually log in in the checkout

---

resources/js/components/Listing/Listing.vue
resources/js/package.js
resources/views/cart/item.blade.php
resources/views/layouts/partials/header/autocomplete/products.blade.php
resources/views/listing/partials/item.blade.php
resources/views/product/partials/images.blade.php

This: https://github.com/rapidez/core/pull/602 was merged in master instead of 2.x

Resize path helper

---

resources/js/stores/useUser.js

The functions from login have only been moved to their own function.
This lays the foundation for having one piece of logic for all ways of logging in, e.g. login-as-customer, social-login etc.
The only responsibility of those modules, would be acquiring a customer token.
3.x: #636

Add loginByToken function

---

resources/js/components/Product/Images.vue

[3.x] Fix image breaking when switching

---

.prettierignore
composer.json
resources/js/callbacks.js
resources/views/cart/queries/fragments/cart.graphql
resources/views/checkout/partials/sidebar.blade.php
resources/views/checkout/steps/agreements.blade.php
resources/views/checkout/steps/place_order.blade.php
src/Http/Controllers/CheckoutController.php

See the checklist of unresolved comments here: https://github.com/rapidez/core/pull/503

Fix merge issues, remove todos

---

resources/js/components/Elements/Slider.vue

Before (the dotted line is the onload event):
After (as you can see the onload can be fired before the style changes):

[2.x] Reduce forced reflow when initialising

---

resources/js/components/Elements/Slider.vue

See: https://github.com/rapidez/core/pull/609

Reduce forced reflow when initialising

---

resources/js/package.js
resources/views/layouts/app.blade.php
tests/DuskTestCaseSetup.php

Init after turbolinks load

---

src/Commands/ElasticsearchIndexer.php

[3.x] Use synonym graph instead of regular synonyms

---

composer.json
tests/DuskTestCase.php

[3.x] Require blade components

---

resources/js/components/GlobalSlideover.vue
resources/js/components/GlobalSlideoverInstance.vue
resources/js/vue-components.js
resources/views/components/slideover/global.blade.php
resources/views/layouts/app.blade.php
resources/views/layouts/partials/global-slideover.blade.php

[3.x] Add global slideover

---

resources/views/layouts/partials/footer.blade.php

See also: https://github.com/rapidez/checkout-theme/pull/157

[3.x] Listen to magento configuration for newsletter

---

resources/views/listing/partials/stats.blade.php
resources/views/listing/products.blade.php
tailwind.config.js

Just some small fixes for:
New:

Small frontend fixes POP

---

resources/js/components/Search/Autocomplete.vue

[2.x] Allow for custom fuzziness in additionals

---

resources/js/stores/useCart.js

This function is already used everywhere else in this file but here.

[3.x] Use updateCart function

---

resources/views/listing/partials/item.blade.php

Selected options stayed selected after filtering and getting a different item in its place. Adding a key here fixes that.

[Instantsearch] Add key to item

---

resources/views/components/input/select/country.blade.php

This will fix the warning in the console and the dusk test that where failing.

Fix country select loop

---

src/Http/Controllers/CategoryController.php
src/Http/Controllers/PageController.php
src/Http/Controllers/ProductController.php
src/Models/Category.php
src/Models/Page.php
src/Models/Product.php
src/Models/Scopes/Product/WithProductAttributesScope.php

See: https://github.com/rapidez/core/pull/728

Remove no-cache from cache-control

---

resources/views/errors/404.blade.php

[2.x] Use @content for 404 content

---

resources/js/components/Search/Autocomplete.vue

#751 but actually 2.x this time

[2.x] Add arbitrary options

---

src/Http/ViewComposers/ConfigComposer.php

[2.x] Use correct show_tax value

---

resources/js/components/Listing/Listing.vue
resources/views/category/overview.blade.php
resources/views/components/listing.blade.php
resources/views/listing/partials/filter/category.blade.php
src/Http/ViewComposers/ConfigComposer.php
src/Models/Category.php

This adds the dynamic max depth on the category filter and the root path on category pages. I've also added the filter heading to make it collapsible.

[Instantsearch] Category filter max depth & root path

---

resources/js/stores/useUser.js

#685 but then inside of the useUser store.

[3.x] Add custom attributes to user store

---

src/Models/Product.php

2.x version: https://github.com/rapidez/core/pull/776

Only use special price when it's lower

---

resources/js/components/Product/AddToCart.vue

[2.x] Don't return early when only 1 child product exists

---

src/Models/Category.php
src/Models/Product.php
src/Models/Traits/Product/Searchable.php
src/Models/Traits/Searchable.php

This PR refactors the searchable models a little.
Removing code that is no longer needed, adressing some todos, reducing model size

Refactor searchable models

---

src/Models/Scopes/Attribute/OnlyProductAttributesScope.php
src/Models/Scopes/Product/WithProductSuperAttributesScope.php

[2.x] Make sure JSON can't be empty

---

resources/js/stores/useCart.js

[3.x] Return 0 instead of void when no taxes

---

resources/views/components/productlist.blade.php

[2.x] Add infinite-scroll false by default

---

resources/js/fetch.js

[2.x] Fix loadingcount going under 0

---

src/Commands/InstallCommand.php

Install additional package requirements from the install command

---

resources/js/components/GraphqlMutation.vue

[3.x] Add debounce to graphql mutation

---

resources/js/fetch.js
resources/js/package.js
resources/js/stores/useFetches.js

[2.x] Maintain a list of fetches to ensure exact loading count

---

src/Widgets/ProductAndCategoryLink.php

ProductAndCategoryLink PHPStan

---

src/RapidezServiceProvider.php

This config should exist but didn't yet.

[3.x] Fix magento-defaults config

---

src/Listeners/Healthcheck/MagentoSettingsHealthcheck.php

This way you can't accidentally forget to set these values as you'll get a warning if they're left on default values

[3.x] Add warning messages for customer configuration

---

src/Listeners/Healthcheck/MagentoSettingsHealthcheck.php

This way you can't accidentally forget to set these values as you'll get a warning if they're left on default values

[2.x] Add warning messages for customer configuration

---

resources/views/components/productlist.blade.php
resources/views/layouts/app.blade.php
resources/views/layouts/config.blade.php
resources/views/layouts/partials/header/autocomplete/products.blade.php
resources/views/listing/partials/item.blade.php
src/Http/Controllers/CategoryController.php
src/Http/Controllers/ConfigController.php

Fixes the missing config values when on a product page & fixes product listings.

[Instantsearch] Add frontend values to config & fix productlist

---

src/Models/Traits/HasAlternatesThroughRewrites.php

This is (apparently---so I'm told) very slightly better for SEO purposes.

[3.x] Also show self as alternate

---

src/Models/Traits/HasAlternatesThroughRewrites.php

[2.x] Also show self as alternate

---

resources/views/components/productlist.blade.php

Just like with https://github.com/rapidez/core/blob/instantsearch/resources/views/components/listing.blade.php to give you full control. Came across this while writing the docs: https://github.com/rapidez/docs/commit/67e168141d9f07161b17d410eb596f325a40eb01#diff-c4bd4e225533416f9d38a25dec4e436684cfc7a49bf4477df9db229445560d54R170-R184

Productlist; merge the attributes in the listing

---

routes/magento-redirects.php
routes/web.php
src/RapidezServiceProvider.php

See also: https://github.com/rapidez/account/pull/68
Adds a bunch more Magento URL redirects that could possibly be relevant. Also moved them to a bespoke file.

[3.x] Add extra magento redirects

---

resources/views/layouts/partials/header.blade.php
resources/views/layouts/partials/header/minicart.blade.php

Within the mobile view the mobile navigation content wasn't aligned. Now it looks pretty on mobile too :D

Aligned mobile content correctly

---

config/rapidez/searchkit.php
resources/views/layouts/partials/header/autocomplete/categories.blade.php
src/Models/Category.php

[Instantsearch] Add category path to categories in autocomplete

---

resources/views/checkout/steps/billing_address.blade.php

See: https://github.com/rapidez/core/pull/892

[3.x] Validate shipping address before sending same as shipping

---

resources/views/layouts/partials/header/minicart.blade.php

[4.x] Add shipping cost to minicart

---

src/Models/ProductOption.php
src/Models/ProductOptionTypeValue.php

See: https://github.com/rapidez/core/pull/911

[3.x] Support negative product option prices

---

src/Models/ProductOption.php
src/Models/ProductOptionTypeValue.php

See: https://github.com/rapidez/core/pull/911

Support negative product option prices

---

lang/en/frontend.php
lang/nl/frontend.php
resources/js/components/User/Login.vue

[3.x] Add error for invalid login

---

lang/nl.json
resources/views/checkout/partials/address.blade.php
resources/views/components/button/toggle.blade.php

Added a toggle that displays fields when the user is a business instead of a private individual. 
Example:
https://github.com/user-attachments/assets/d805f55c-7537-45c1-9ac3-927d8f1a47ad

Private / Business toggle in checkout

---

composer.json

Now the elasticsearch package can simply follow semver

Updated scout elasticsearch dependency

---

resources/js/components/GraphqlMutation.vue

[3.x] Add import for useDebounceFn

---

resources/js/components/GraphqlMutation.vue

[4.x] Add import for useDebounceFn

---

resources/js/components/User/Login.vue
resources/js/fetch.js
resources/js/package.js

Not having a type here caused there to be undefined behavior. This would currently result in a notification without an actual background, but it fully depends on how styling is implemented.

[4.x] Fix all cases of empty Notify usage in core & set default

---

resources/js/components/GraphqlMutation.vue
resources/views/checkout/steps/billing_address.blade.php

This fixes a bug where changing anything in your shipping address would make the billing address reappear in your checkout.

[4.x] Add watch ignore and ignore 'same_as_shipping' to fix checkout bug

---

resources/views/components/productlist.blade.php

Allows easy changing of what the productlist looks like without needing to overwrite/make your own component.

[4.x] Add productlist slot

---

composer.json

Alternative for: https://github.com/rapidez/core/pull/988, fix in: https://github.com/laravel/framework/pull/56779

Skip bugged Laravel version

---

resources/views/components/productlist.blade.php

See the examples in the component comments and this: https://github.com/rapidez/statamic-query-builder/pull/12

More flexible productlist component

---

tests/playwright/pages/BasePage.js

So we can do things like:
```
await new BasePage(page).screenshot('fullpage-footer', {
mask: [await page.getByTestId('masked')],
})
```

Playwright extendable screenshot options

---

package.json

So we can use this with npm workspaces like:
```
"workspaces": [
"vendor/rapidez/*"
]
```
And for example do this: `import { BasePage } from '@rapidez/core/tests/playwright/pages/BasePage.js'`

Package.json name and version

---

resources/js/stores/useCart.js

#1005 didn't fix it, but this seems to do the trick.

[4.x] Use setTimeout around mask section in useCart
